// ============================================
// CIVICS DATA - Občanská výchova (4.-9. třída)
// ============================================

GRADE_TOPICS.civics = {
    '4': ['ov4_rodina','ov4_skola','ov4_pravidla','ov4_bezpecnost','ov4_zdravi'],
    '5': ['ov5_obec','ov5_stat','ov5_symboly','ov5_prava','ov5_media'],
    '6': ['ov6_spolecnost','ov6_pravo','ov6_hospodarstvi','ov6_demokracie','ov6_kultura'],
    '7': ['ov7_ustava','ov7_statorgany','ov7_volby','ov7_eu','ov7_globalprob'],
    '8': ['ov8_pravni','ov8_finance','ov8_trh','ov8_politika','ov8_mezinarodka'],
    '9': ['ov9_filozofie','ov9_etika','ov9_lidprav','ov9_obcprav','ov9_pracprav']
};

TOPIC_NAMES.ov4_rodina='👨‍👩‍👧 Rodina'; TOPIC_NAMES.ov4_skola='🏫 Škola a třída'; TOPIC_NAMES.ov4_pravidla='📋 Pravidla soužití';
TOPIC_NAMES.ov4_bezpecnost='🚦 Bezpečnost'; TOPIC_NAMES.ov4_zdravi='❤️ Zdraví';
TOPIC_NAMES.ov5_obec='🏘️ Obec a kraj'; TOPIC_NAMES.ov5_stat='🏛️ Stát'; TOPIC_NAMES.ov5_symboly='🇨🇿 Státní symboly';
TOPIC_NAMES.ov5_prava='⚖️ Práva dítěte'; TOPIC_NAMES.ov5_media='📺 Média';
TOPIC_NAMES.ov6_spolecnost='👥 Společnost'; TOPIC_NAMES.ov6_pravo='⚖️ Právo'; TOPIC_NAMES.ov6_hospodarstvi='💰 Hospodářství';
TOPIC_NAMES.ov6_demokracie='🗳️ Demokracie'; TOPIC_NAMES.ov6_kultura='🎭 Kultura';
TOPIC_NAMES.ov7_ustava='📜 Ústava'; TOPIC_NAMES.ov7_statorgany='🏛️ Státní orgány'; TOPIC_NAMES.ov7_volby='🗳️ Volby';
TOPIC_NAMES.ov7_eu='🇪🇺 Evropská unie'; TOPIC_NAMES.ov7_globalprob='🌍 Globální problémy';
TOPIC_NAMES.ov8_pravni='⚖️ Právní systém'; TOPIC_NAMES.ov8_finance='💳 Finanční gramotnost'; TOPIC_NAMES.ov8_trh='📊 Trh a ekonomika';
TOPIC_NAMES.ov8_politika='🏛️ Politické strany'; TOPIC_NAMES.ov8_mezinarodka='🌐 Mezinárodní organizace';
TOPIC_NAMES.ov9_filozofie='🤔 Filozofie'; TOPIC_NAMES.ov9_etika='💡 Etika'; TOPIC_NAMES.ov9_lidprav='✊ Lidská práva';
TOPIC_NAMES.ov9_obcprav='📜 Občanské právo'; TOPIC_NAMES.ov9_pracprav='💼 Pracovní právo';

DATA.ov4_rodina=[{q:'Nejbližší rodina = ...? rodina',a:'uzka',h:'Jaká:'},{q:'Prarodiče jsou...?',a:'babicka a dedecek',h:'Kdo:'},{q:'Sourozenci jsou...?',a:'bratri a sestry',h:'Kdo:'},{q:'Neúplná rodina = chybí jeden...?',a:'rodic',h:'Kdo:'},{q:'Domácnost vede kdo?',a:'rodice',h:'Kdo:'},{q:'Příjmení se dědí po...?',a:'rodicich',h:'Po kom:'},{q:'Rodinný rozpočet = příjmy a...?',a:'vydaje',h:'Co:'},{q:'Soužití v rodině vyžaduje...?',a:'respekt',h:'Co:'},{q:'Rodný list dostaneme po...?',a:'narozeni',h:'Po čem:'},{q:'Rodina poskytuje dítěti...?',a:'bezpeci',h:'Co:'},{q:'Povinnost dětí je chodit do...?',a:'skoly',h:'Kam:'},{q:'Rodinné tradice jsou např. ...?',a:'vanoce',h:'Příklad:'},{q:'Svatba je uzavření...?',a:'manzelstvi',h:'Čeho:'},{q:'Adopce znamená...?',a:'osvojeni',h:'Co:'},{q:'Pěstounská péče je forma...?',a:'nahradni pece',h:'Čeho:'}];
DATA.ov4_skola=[{q:'Základní škola má...? ročníků',a:'9',h:'Kolik:'},{q:'1. stupeň ZŠ: ročníky 1-...?',a:'5',h:'Do:'},{q:'2. stupeň ZŠ: ročníky 6-...?',a:'9',h:'Do:'},{q:'Ředitel školy řídí...?',a:'skolu',h:'Co:'},{q:'Třídní učitel se stará o...?',a:'tridu',h:'Co:'},{q:'Žákovská knížka slouží k...?',a:'znamkam',h:'K čemu:'},{q:'Školní řád stanovuje...?',a:'pravidla',h:'Co:'},{q:'Povinná školní docházka je...? let',a:'9',h:'Kolik:'},{q:'Školní parlament zastupuje...?',a:'zaky',h:'Koho:'},{q:'Šikana je...?',a:'ublihovani',h:'Co:'},{q:'Šikanu je třeba...?',a:'nahlasit',h:'Co udělat:'},{q:'Omluvenka slouží k omluvení...?',a:'absence',h:'Čeho:'},{q:'Přestávka trvá...? minut (malá)',a:'10',h:'Kolik:'},{q:'Vyučovací hodina trvá...? minut',a:'45',h:'Kolik:'},{q:'Známka 1 je...?',a:'vyborny',h:'Jaká:'}];
DATA.ov4_pravidla=[{q:'Zákon je...?',a:'zavazne pravidlo',h:'Co:'},{q:'Ústava je...? zákon',a:'nejdulezitejsi',h:'Jaký:'},{q:'Pravidla silničního provozu chrání...?',a:'bezpecnost',h:'Co:'},{q:'Tolerance znamená...?',a:'snaselivost',h:'Co:'},{q:'Spravedlnost znamená...?',a:'rovne zachazeni',h:'Co:'},{q:'Slušné chování zahrnuje...?',a:'zdvorilost',h:'Co:'},{q:'Při setkání se zdravíme...?',a:'pozdravem',h:'Čím:'},{q:'Pomoc druhým se nazývá...?',a:'solidarita',h:'Jak:'},{q:'Vandalismus je...?',a:'niceni majetku',h:'Co:'},{q:'Krádež je...?',a:'trestny cin',h:'Co:'},{q:'Lhaní je...?',a:'nespravne',h:'Jaké:'},{q:'Úcta ke starším je...?',a:'dulezita',h:'Jaká:'},{q:'Domovní řád platí v...?',a:'dome',h:'Kde:'},{q:'Cestovní řád platí v...?',a:'doprave',h:'Kde:'},{q:'Školní řád platí ve...?',a:'skole',h:'Kde:'}];
DATA.ov4_bezpecnost=[{q:'Tísňová linka je...?',a:'112',h:'Číslo:'},{q:'Hasiči mají číslo...?',a:'150',h:'Číslo:'},{q:'Záchranná služba...?',a:'155',h:'Číslo:'},{q:'Policie ČR...?',a:'158',h:'Číslo:'},{q:'Na přechodu svítí...? barvy',a:'3',h:'Kolik:'},{q:'Zelená na semaforu = ...?',a:'jdi',h:'Co:'},{q:'Červená na semaforu = ...?',a:'stuj',h:'Co:'},{q:'Chodec chodí po...?',a:'chodniku',h:'Kde:'},{q:'Cyklista musí mít...?',a:'helmu',h:'Co:'},{q:'Při požáru voláme...?',a:'150',h:'Číslo:'},{q:'Při nehodě voláme...?',a:'112',h:'Číslo:'},{q:'Na kole ve tmě svítíme...?',a:'svetlem',h:'Čím:'},{q:'Bezpečnostní pás v autě je...?',a:'povinny',h:'Jaký:'},{q:'Dětská autosedačka do...? let',a:'12',h:'Do kolika:'},{q:'Přechod pro chodce je...?',a:'zebra',h:'Co:'}];
DATA.ov4_zdravi=[{q:'Kolik hodin by mělo dítě spát?',a:'10',h:'Asi kolik:'},{q:'Ovoce a zelenina obsahují...?',a:'vitaminy',h:'Co:'},{q:'Pohyb na čerstvém vzduchu je...?',a:'zdravy',h:'Jaký:'},{q:'Hygiena znamená...?',a:'cistota',h:'Co:'},{q:'Zuby si čistíme...? denně (min.)',a:'2',h:'Kolikrát:'},{q:'Správné držení těla = správný...?',a:'posed',h:'Co:'},{q:'Nemocný člověk navštíví...?',a:'lekare',h:'Koho:'},{q:'Očkování chrání před...?',a:'nemocemi',h:'Čím:'},{q:'Vitamín C je v...?',a:'ovoci',h:'V čem:'},{q:'Pitný režim = dostatek...?',a:'tekutin',h:'Čeho:'},{q:'Alkohol je pro děti...?',a:'zakazany',h:'Jaký:'},{q:'Cigarety jsou...? pro zdraví',a:'skodlive',h:'Jaké:'},{q:'Sport je...? pro zdraví',a:'prosperny',h:'Jaký:'},{q:'Alergie je...? reakce',a:'prehnana',h:'Jaká:'},{q:'První pomoc: při krvácení...?',a:'zastavit krvaceni',h:'Co:'}];

DATA.ov5_obec=[{q:'V čele obce stojí...?',a:'starosta',h:'Kdo:'},{q:'Zastupitelstvo obce volí...?',a:'obcane',h:'Kdo:'},{q:'Městský úřad spravuje...?',a:'mesto',h:'Co:'},{q:'Kolik krajů má ČR?',a:'14',h:'Kolik:'},{q:'V čele kraje stojí...?',a:'hejtman',h:'Kdo:'},{q:'Krajský úřad sídlí v krajském...?',a:'meste',h:'Kde:'},{q:'Obec se stará o silnice,...?',a:'skoly parky',h:'O co dál:'},{q:'Obecní rozpočet = příjmy a...?',a:'vydaje',h:'Co:'},{q:'Volby do zastupitelstva jsou každé...? roky',a:'4',h:'Kolik:'},{q:'Praha je...? město',a:'hlavni',h:'Jaké:'},{q:'Matriční úřad eviduje...?',a:'narozeni a smrtky',h:'Co:'},{q:'Stavební úřad povoluje...?',a:'stavby',h:'Co:'},{q:'Obecní policie dohlíží na...?',a:'poradek',h:'Na co:'},{q:'Zastupitelstvo schvaluje...?',a:'rozpocet',h:'Co:'},{q:'Občan obce má právo...?',a:'volit',h:'Jaké:'}];
DATA.ov5_stat=[{q:'ČR je...? republika',a:'parlamentni',h:'Jaká:'},{q:'Prezident ČR sídlí na...?',a:'hrade',h:'Kde:'},{q:'Hlavní město ČR je...?',a:'Praha',h:'Jaké:'},{q:'ČR vznikla roku...?',a:'1993',h:'Rok:'},{q:'Před ČR existovalo...?',a:'ceskoslovensko',h:'Co:'},{q:'Měna ČR je...?',a:'ceska koruna',h:'Jaká:'},{q:'Hymna ČR je...?',a:'kde domov muj',h:'Jaká:'},{q:'Státní svátek 28. října připomíná...?',a:'vznik csr',h:'Co:'},{q:'Prezident je volen na...? let',a:'5',h:'Kolik:'},{q:'Premiér řídí...?',a:'vladu',h:'Co:'},{q:'Poslanecká sněmovna má...? poslanců',a:'200',h:'Kolik:'},{q:'Senát má...? senátorů',a:'81',h:'Kolik:'},{q:'Soudní moc vykonávají...?',a:'soudy',h:'Kdo:'},{q:'Zákonodárná moc = ...?',a:'parlament',h:'Co:'},{q:'Výkonná moc = ...?',a:'vlada',h:'Co:'}];
DATA.ov5_symboly=[{q:'Státní barvy ČR jsou...?',a:'bila cervena modra',h:'Jaké:'},{q:'Velký státní znak má...?',a:'lva',h:'Co:'},{q:'Státní vlajka má...? pruhy',a:'2',h:'Kolik:'},{q:'Modrý klín na vlajce je...?',a:'vlevo',h:'Kde:'},{q:'Hymna ČR: „Kde domov..."?',a:'muj',h:'Doplň:'},{q:'Autor hymny (text)?',a:'josef kajetan tyl',h:'Kdo:'},{q:'Autor hymny (hudba)?',a:'frantisek skroup',h:'Kdo:'},{q:'Státní pečeť potvrzuje...?',a:'dokumenty',h:'Co:'},{q:'Prezidentská standarta visí na...?',a:'hrade',h:'Kde:'},{q:'Lev na znaku je...? barvy',a:'bile',h:'Jaké:'},{q:'Moravská orlice je...? barvy',a:'cervene',h:'Jaké:'},{q:'Slezská orlice je...? barvy',a:'cerne',h:'Jaké:'},{q:'Státní svátek 1. ledna je...?',a:'den obnovy',h:'Co:'},{q:'17. listopadu slavíme...?',a:'den boje za svobodu',h:'Co:'},{q:'Malý státní znak obsahuje...?',a:'lva',h:'Co:'}];
DATA.ov5_prava=[{q:'Úmluva o právech dítěte je od...?',a:'osn',h:'Od koho:'},{q:'Dítě má právo na...?',a:'vzdelani',h:'Na co:'},{q:'Dítě má právo na...? péči',a:'zdravotni',h:'Jakou:'},{q:'Dětská práce je...?',a:'zakazana',h:'Jaká:'},{q:'Každé dítě má právo na...?',a:'jmeno',h:'Na co:'},{q:'Dítě má právo vyjádřit svůj...?',a:'nazor',h:'Co:'},{q:'Diskriminace znamená...?',a:'znevyhodnovani',h:'Co:'},{q:'Šikana porušuje právo na...?',a:'bezpeci',h:'Na co:'},{q:'UNICEF pomáhá...?',a:'detem',h:'Komu:'},{q:'Zletilost v ČR nastává v...? letech',a:'18',h:'V kolika:'},{q:'Právo volit je od...? let',a:'18',h:'Od kolika:'},{q:'Povinná školní docházka do...? let',a:'15',h:'Do kolika (cca):'},{q:'Trestní odpovědnost od...? let',a:'15',h:'Od kolika:'},{q:'Každý má právo na...?',a:'zivot',h:'Na co:'},{q:'Rovnost znamená, že všichni jsou si...?',a:'rovni',h:'Jací:'}];
DATA.ov5_media=[{q:'Média slouží k šíření...?',a:'informaci',h:'Čeho:'},{q:'Televize je...? médium',a:'audiovizualni',h:'Jaké:'},{q:'Noviny jsou...? médium',a:'tistene',h:'Jaké:'},{q:'Internet je...? médium',a:'elektronicke',h:'Jaké:'},{q:'Reklama propaguje...?',a:'vyrobky',h:'Co:'},{q:'Zpravodajství informuje o...?',a:'udalostech',h:'O čem:'},{q:'Fake news jsou...?',a:'falesne zpravy',h:'Co:'},{q:'Hoax je...?',a:'podvrh',h:'Co:'},{q:'Kritické myšlení = ověřovat...?',a:'informace',h:'Co:'},{q:'Dezinformace = záměrně...?',a:'falesna informace',h:'Co:'},{q:'Veřejnoprávní TV v ČR je...?',a:'ceska televize',h:'Jaká:'},{q:'Tiskový zákon reguluje...?',a:'media',h:'Co:'},{q:'Cenzura = zákaz...?',a:'informaci',h:'Čeho:'},{q:'Svoboda tisku je...?',a:'zakladni pravo',h:'Co:'},{q:'Sociální sítě jsou...?',a:'online platformy',h:'Co:'}];

DATA.ov6_spolecnost=[{q:'Socializace je proces...?',a:'zaclenovani do spolecnosti',h:'Co:'},{q:'Norma je...?',a:'pravidlo chovani',h:'Co:'},{q:'Role ve společnosti = ...?',a:'socialni role',h:'Co:'},{q:'Rodina je...? skupina',a:'socialni',h:'Jaká:'},{q:'Konflikt je...?',a:'stret zajmu',h:'Co:'},{q:'Kompromis je...?',a:'vzajemny ustupek',h:'Co:'},{q:'Předsudek je...?',a:'neoduvodneny nazor',h:'Co:'},{q:'Stereotyp je...?',a:'zjednoduseny obraz',h:'Co:'},{q:'Rasismus je...?',a:'diskriminace dle rasy',h:'Co:'},{q:'Xenofobie je strach z...?',a:'cizincu',h:'Z čeho:'},{q:'Multikulturní společnost = ...?',a:'vice kultur',h:'Co:'},{q:'Dobrovolnictví je...?',a:'bezplatna pomoc',h:'Co:'},{q:'Charita pomáhá...?',a:'potrebnym',h:'Komu:'},{q:'Subkultura je...?',a:'mensinova kultura',h:'Co:'},{q:'Globalizace propojuje...?',a:'svet',h:'Co:'}];
DATA.ov6_pravo=[{q:'Zákon vytváří...?',a:'parlament',h:'Kdo:'},{q:'Soud rozhoduje o...?',a:'vine',h:'O čem:'},{q:'Přestupek je menší...?',a:'poruseni zakona',h:'Co:'},{q:'Trestný čin je závažné...?',a:'poruseni zakona',h:'Co:'},{q:'Obžalovaný má právo na...?',a:'obhajce',h:'Na co:'},{q:'Presumpce neviny = člověk je...?',a:'neviny do rozsudku',h:'Co:'},{q:'Svědek vypovídá u...?',a:'soudu',h:'Kde:'},{q:'Advokát zastupuje...?',a:'klienta',h:'Koho:'},{q:'Soudce rozhoduje...?',a:'nezavisle',h:'Jak:'},{q:'Policie vyšetřuje...?',a:'trestne ciny',h:'Co:'},{q:'Občanský zákoník upravuje...?',a:'obcanske vztahy',h:'Co:'},{q:'Trestní zákoník upravuje...?',a:'tresty',h:'Co:'},{q:'Pokuta je...?',a:'penezni trest',h:'Co:'},{q:'Vězení je trest...?',a:'odneti svobody',h:'Jaký:'},{q:'Ústavní soud hlídá...?',a:'ustavnost',h:'Co:'}];
DATA.ov6_hospodarstvi=[{q:'Ekonomika studuje...?',a:'hospodareni',h:'Co:'},{q:'Nabídka a poptávka tvoří...?',a:'trh',h:'Co:'},{q:'Inflace je růst...?',a:'cen',h:'Čeho:'},{q:'Daně platíme...?',a:'statu',h:'Komu:'},{q:'DPH je daň z...?',a:'pridane hodnoty',h:'Z čeho:'},{q:'Zaměstnavatel platí zaměstnanci...?',a:'mzdu',h:'Co:'},{q:'Nezaměstnanost = lidé bez...?',a:'prace',h:'Bez čeho:'},{q:'HDP měří...?',a:'ekonomicky vykon',h:'Co:'},{q:'ČNB je...?',a:'ceska narodni banka',h:'Co:'},{q:'Rozpočet státu schvaluje...?',a:'parlament',h:'Kdo:'},{q:'Podnikatel podniká za účelem...?',a:'zisku',h:'Čeho:'},{q:'Živnostník má...?',a:'zivnostensky list',h:'Co:'},{q:'Monopol = jeden...? na trhu',a:'prodejce',h:'Co:'},{q:'Konkurence zlepšuje...?',a:'kvalitu',h:'Co:'},{q:'Export = ...?',a:'vyvoz',h:'Co:'}];
DATA.ov6_demokracie=[{q:'Demokracie = vláda...?',a:'lidu',h:'Koho:'},{q:'Opak demokracie je...?',a:'diktatura',h:'Co:'},{q:'Volební právo mají občané od...? let',a:'18',h:'Od kolika:'},{q:'Volby musí být...?',a:'svobodne',h:'Jaké:'},{q:'Tajné hlasování zajišťuje...?',a:'plentu',h:'Co (za co jdeme):'},{q:'Politická strana zastupuje...?',a:'obcany',h:'Koho:'},{q:'Opozice kritizuje...?',a:'vladu',h:'Koho:'},{q:'Koalice je spojení...?',a:'stran',h:'Čeho:'},{q:'Referendum je...?',a:'lidove hlasovani',h:'Co:'},{q:'Petiční právo = právo na...?',a:'petici',h:'Na co:'},{q:'Shromažďovací právo = právo...?',a:'shromazdovat se',h:'Jaké:'},{q:'Svoboda slova = právo...?',a:'vyjadrit nazor',h:'Jaké:'},{q:'Totalita potlačuje...?',a:'svobodu',h:'Co:'},{q:'Dělba moci: 3 složky',a:'zakonodar vykon soud',h:'Jaké:'},{q:'Listina základních práv je součástí...?',a:'ustavy',h:'Čeho:'}];
DATA.ov6_kultura=[{q:'Kultura zahrnuje umění,...?',a:'tradice zvyky',h:'Co dál:'},{q:'UNESCO chrání...?',a:'kulturni dedictvi',h:'Co:'},{q:'Památka zapsaná UNESCO v ČR: ...?',a:'praha',h:'Příklad:'},{q:'Divadlo je forma...?',a:'umeni',h:'Čeho:'},{q:'Muzeum uchovává...?',a:'sbirky',h:'Co:'},{q:'Galerie vystavuje...?',a:'umeni',h:'Co:'},{q:'Tradice je...?',a:'zvyk predavany',h:'Co:'},{q:'Folklór je lidová...?',a:'kultura',h:'Co:'},{q:'Národní divadlo je v...?',a:'praze',h:'Kde:'},{q:'Knihovna půjčuje...?',a:'knihy',h:'Co:'},{q:'Kulturní dědictví = hodnoty z...?',a:'minulosti',h:'Odkud:'},{q:'Architektura je umění...?',a:'stavitelstvi',h:'Čeho:'},{q:'Film je...? umění',a:'audiovizualni',h:'Jaké:'},{q:'Socha je dílo...?',a:'socharstvi',h:'Čeho:'},{q:'Obraz je dílo...?',a:'malirstvi',h:'Čeho:'}];

DATA.ov7_ustava=[{q:'Ústava ČR platí od roku...?',a:'1993',h:'Od:'},{q:'Ústava je...? zákon země',a:'nejvyssi',h:'Jaký:'},{q:'Součástí Ústavy je...?',a:'listina zakladnich prav',h:'Co:'},{q:'Moc zákonodárná = ...?',a:'parlament',h:'Co:'},{q:'Moc výkonná = ...?',a:'vlada a prezident',h:'Co:'},{q:'Moc soudní = ...?',a:'soudy',h:'Co:'},{q:'Parlament ČR má...? komory',a:'2',h:'Kolik:'},{q:'Dolní komora = ...?',a:'poslanecka snemovna',h:'Co:'},{q:'Horní komora = ...?',a:'senat',h:'Co:'},{q:'Preambule je...? Ústavy',a:'uvod',h:'Co:'},{q:'Ústava má...? hlav',a:'8',h:'Kolik:'},{q:'Ústavní soud sídlí v...?',a:'brne',h:'Kde:'},{q:'Změna Ústavy vyžaduje...? většinu',a:'trypetinovou',h:'Jakou:'},{q:'Lidská práva jsou...?',a:'nezadatelna',h:'Jaká:'},{q:'Ústava zaručuje dělbu...?',a:'moci',h:'Čeho:'}];
DATA.ov7_statorgany=[{q:'Prezident je volen na...? let',a:'5',h:'Kolik:'},{q:'Prezident může být zvolen max...?krát',a:'2',h:'Kolikrát:'},{q:'Vládu jmenuje...?',a:'prezident',h:'Kdo:'},{q:'Premiér je předseda...?',a:'vlady',h:'Čeho:'},{q:'Poslanec je volen na...? roky',a:'4',h:'Kolik:'},{q:'Senátor je volen na...? let',a:'6',h:'Kolik:'},{q:'Nejvyšší soud sídlí v...?',a:'brne',h:'Kde:'},{q:'Prezident sídlí na...?',a:'prazskem hrade',h:'Kde:'},{q:'NKÚ kontroluje...?',a:'statni finance',h:'Co:'},{q:'Ombudsman chrání občany před...?',a:'uradni moci',h:'Před čím:'},{q:'Česká národní banka spravuje...?',a:'menu',h:'Co:'},{q:'Vláda má odpovědnost vůči...?',a:'snemovne',h:'Komu:'},{q:'Státní zastupitelství zastupuje...?',a:'stat v trest. rizeni',h:'Koho:'},{q:'Krajský soud je...? instance',a:'druha',h:'Jaká:'},{q:'Okresní soud je...? instance',a:'prvni',h:'Jaká:'}];
DATA.ov7_volby=[{q:'Volby do Sněmovny jsou každé...? roky',a:'4',h:'Kolik:'},{q:'Do Senátu se volí každé...? roky',a:'2',h:'Kolik (třetina):'},{q:'Prezidentské volby jsou každých...? let',a:'5',h:'Kolik:'},{q:'Komunální volby = volby do...?',a:'zastupitelstev obci',h:'Kam:'},{q:'Aktivní volební právo od...? let',a:'18',h:'Od kolika:'},{q:'Pasivní vol. právo do Sněmovny od...? let',a:'21',h:'Od kolika:'},{q:'Pasivní vol. právo do Senátu od...? let',a:'40',h:'Od kolika:'},{q:'Pasivní vol. právo prezidenta od...? let',a:'40',h:'Od kolika:'},{q:'Volby musí být tajné a...?',a:'svobodne',h:'Jaké:'},{q:'Volební komise sčítá...?',a:'hlasy',h:'Co:'},{q:'Volební kampaň propaguje...?',a:'kandidaty',h:'Koho:'},{q:'Mandát = pověření...?',a:'zastupovat',h:'K čemu:'},{q:'Kvórum = minimální...?',a:'ucast',h:'Co:'},{q:'Koalice vzniká po...?',a:'volbach',h:'Po čem:'},{q:'Opoziční strany...?',a:'nevladnou',h:'Co:'}];
DATA.ov7_eu=[{q:'EU vznikla roku...? (Maastricht)',a:'1993',h:'Rok:'},{q:'ČR vstoupila do EU roku...?',a:'2004',h:'Rok:'},{q:'Kolik členských zemí má EU (cca)?',a:'27',h:'Kolik:'},{q:'Měna EU je...?',a:'euro',h:'Jaká:'},{q:'Sídlo Evropské komise je v...?',a:'bruselu',h:'Kde:'},{q:'Evropský parlament sídlí ve...?',a:'strasburku',h:'Kde:'},{q:'Vlajka EU má...? hvězd',a:'12',h:'Kolik:'},{q:'Hymna EU je od...?',a:'beethovena',h:'Od koho:'},{q:'Schengenský prostor = volný...?',a:'pohyb',h:'Co:'},{q:'ČR platí...? (měna)',a:'korunou',h:'Čím:'},{q:'Předseda Evropské rady = ...?',a:'nejvyssi predstavitel',h:'Kdo:'},{q:'Europoslanec zastupuje ČR v...?',a:'evropskem parlamentu',h:'Kde:'},{q:'Jednotný trh EU zajišťuje volný pohyb...?',a:'zbozi a osob',h:'Čeho:'},{q:'NATO je...? organizace',a:'vojenska',h:'Jaká:'},{q:'ČR je členem NATO od roku...?',a:'1999',h:'Od:'}];
DATA.ov7_globalprob=[{q:'Globální oteplování způsobuje...?',a:'sklenikove plyny',h:'Co:'},{q:'Chudoba postihuje...? zemí',a:'rozvojove',h:'Jaké:'},{q:'Terorismus ohrožuje...?',a:'bezpecnost',h:'Co:'},{q:'Migrace je...?',a:'stehovani lidi',h:'Co:'},{q:'Uprchlík prchá před...?',a:'nebezpecim',h:'Před čím:'},{q:'OSN se zabývá...?',a:'mirem',h:'Čím:'},{q:'WHO řeší problémy...?',a:'zdravotnictvi',h:'Čeho:'},{q:'Odlesňování hrozí zejména v...?',a:'tropech',h:'Kde:'},{q:'Znečištění oceánů plasty je...?',a:'globalny problem',h:'Co:'},{q:'Přelidnění hrozí zejména v...?',a:'asii a africe',h:'Kde:'},{q:'Udržitelný rozvoj = rozvoj bez...?',a:'poskozeni budoucnosti',h:'Bez čeho:'},{q:'Fair trade = ...?',a:'spravedlivy obchod',h:'Co:'},{q:'Recyklace pomáhá...?',a:'zivotnimu prostredi',h:'Čemu:'},{q:'Obnovitelné zdroje jsou...?',a:'slunce vitr voda',h:'Jaké:'},{q:'Kyotský protokol řeší...?',a:'emise',h:'Co:'}];

DATA.ov8_pravni=[{q:'Občanské právo řeší...?',a:'majetkove vztahy',h:'Co:'},{q:'Trestní právo trestá...?',a:'trestne ciny',h:'Co:'},{q:'Rodinné právo řeší...?',a:'rodinne vztahy',h:'Co:'},{q:'Pracovní právo chrání...?',a:'zamestnance',h:'Koho:'},{q:'Obchodní právo upravuje...?',a:'podnikani',h:'Co:'},{q:'Správní právo řeší vztah občan-...?',a:'stat',h:'Kdo:'},{q:'Soudce musí být...?',a:'nezavisly',h:'Jaký:'},{q:'Právní řád = soubor...?',a:'zakonu',h:'Čeho:'},{q:'Zákon schvaluje...?',a:'parlament',h:'Kdo:'},{q:'Vyhláška je vydávána...?',a:'ministerstvem',h:'Kým:'},{q:'Nařízení vlády vydává...?',a:'vlada',h:'Kdo:'},{q:'Sbírka zákonů obsahuje...?',a:'zakony',h:'Co:'},{q:'Právní subjektivita = způsobilost mít...?',a:'prava',h:'Co:'},{q:'Plná svéprávnost od...? let',a:'18',h:'Od kolika:'},{q:'Smlouva je právní...?',a:'ukon',h:'Co:'}];
DATA.ov8_finance=[{q:'Úrok je odměna za...?',a:'pujcku',h:'Za co:'},{q:'Spoření = odkládání peněz na...?',a:'ucet',h:'Kam:'},{q:'Hypotéka = úvěr na...?',a:'bydleni',h:'Na co:'},{q:'Pojištění chrání před...?',a:'rizikem',h:'Před čím:'},{q:'Kreditní karta = ...? peníze',a:'pujcene',h:'Jaké:'},{q:'Debetní karta = ...? peníze',a:'vlastni',h:'Jaké:'},{q:'Rozpočet = plán příjmů a...?',a:'vydaju',h:'Čeho:'},{q:'Dluh = povinnost...?',a:'splatit',h:'Co:'},{q:'Investice = vložení peněz za účelem...?',a:'zisku',h:'Čeho:'},{q:'Inflace snižuje...?',a:'hodnotu penez',h:'Co:'},{q:'Daň z příjmu platí...?',a:'zamestnanec',h:'Kdo:'},{q:'Sociální pojištění platí...?',a:'zamestnanec i zamestnavatel',h:'Kdo:'},{q:'Bankovní účet slouží k...?',a:'ukladani penez',h:'K čemu:'},{q:'Úvěr = ...?',a:'pujcka',h:'Co:'},{q:'Exekuce = vymáhání...?',a:'dluhu',h:'Čeho:'}];
DATA.ov8_trh=[{q:'Nabídka roste, cena...?',a:'klesa',h:'Co dělá:'},{q:'Poptávka roste, cena...?',a:'roste',h:'Co dělá:'},{q:'Monopol = jeden...?',a:'prodejce',h:'Co:'},{q:'Oligopol = málo...?',a:'prodejcu',h:'Kolik:'},{q:'Konkurence zlepšuje...?',a:'kvalitu a cenu',h:'Co:'},{q:'Tržní ekonomika = rozhoduje...?',a:'trh',h:'Co:'},{q:'Plánovaná ekonomika = rozhoduje...?',a:'stat',h:'Co:'},{q:'Smíšená ekonomika = kombinace...?',a:'trhu a statu',h:'Čeho:'},{q:'GDP/HDP měří...?',a:'ekonomicky vykon',h:'Co:'},{q:'Recese = ekonomický...?',a:'pokles',h:'Co:'},{q:'Konjunktura = ekonomický...?',a:'rust',h:'Co:'},{q:'Akcie = podíl ve...?',a:'firme',h:'V čem:'},{q:'Burza obchoduje s...?',a:'cennymi papiry',h:'S čím:'},{q:'Podnikatel nese...?',a:'riziko',h:'Co:'},{q:'Zisk = příjmy mínus...?',a:'naklady',h:'Co:'}];
DATA.ov8_politika=[{q:'Pravice zdůrazňuje...?',a:'svobodu jedince',h:'Co:'},{q:'Levice zdůrazňuje...?',a:'rovnost',h:'Co:'},{q:'Liberalismus prosazuje...?',a:'svobodu',h:'Co:'},{q:'Konzervatismus chrání...?',a:'tradice',h:'Co:'},{q:'Socialismus zdůrazňuje...?',a:'socialni spravedlnost',h:'Co:'},{q:'Populismus slibuje...?',a:'jednoducha reseni',h:'Co:'},{q:'Extremismus je...?',a:'krajni nazor',h:'Co:'},{q:'Lobbying = prosazování...?',a:'zajmu',h:'Čeho:'},{q:'Korupce = ...?',a:'uplatkarstvi',h:'Co:'},{q:'Transparentnost = ...?',a:'pruhlednost',h:'Co:'},{q:'Občanská společnost = ...?',a:'aktivni obcane',h:'Co:'},{q:'NGO je...?',a:'neziskova organizace',h:'Co:'},{q:'Veřejné mínění = názor...?',a:'verejnosti',h:'Koho:'},{q:'Politický program obsahuje...?',a:'cile strany',h:'Co:'},{q:'Ideologie je soubor...?',a:'politickych idei',h:'Čeho:'}];
DATA.ov8_mezinarodka=[{q:'OSN vznikla roku...?',a:'1945',h:'Rok:'},{q:'Sídlo OSN je v...?',a:'new yorku',h:'Kde:'},{q:'Kolik členů má OSN (cca)?',a:'193',h:'Kolik:'},{q:'NATO je...? aliance',a:'vojenska',h:'Jaká:'},{q:'EU sdružuje evropské...?',a:'staty',h:'Co:'},{q:'Červený kříž pomáhá při...?',a:'katastrofach',h:'Při čem:'},{q:'WHO řeší...?',a:'zdravotnictvi',h:'Co:'},{q:'UNICEF chrání...?',a:'deti',h:'Koho:'},{q:'Rada bezpečnosti OSN má...? stálých členů',a:'5',h:'Kolik:'},{q:'Amnesty International chrání...?',a:'lidska prava',h:'Co:'},{q:'Greenpeace chrání...?',a:'zivotni prostredi',h:'Co:'},{q:'G7 sdružuje...? zemí',a:'7',h:'Kolik:'},{q:'Mezinárodní soudní dvůr sídlí v...?',a:'haagu',h:'Kde:'},{q:'WTO řeší...?',a:'svetovyobchod',h:'Co:'},{q:'MMF = mezinárodní...?',a:'menovy fond',h:'Co:'}];

DATA.ov9_filozofie=[{q:'Sokrates je známý výrokem „Vím, že..."',a:'nic nevim',h:'Doplň:'},{q:'Platón napsal...?',a:'ústavu',h:'Co:'},{q:'Aristoteles byl žákem...?',a:'platona',h:'Koho:'},{q:'Descartes: „Myslím, tedy..."',a:'jsem',h:'Doplň:'},{q:'Filozofie = láska k...?',a:'moudrosti',h:'K čemu:'},{q:'Etika zkoumá...?',a:'morálku',h:'Co:'},{q:'Logika zkoumá...?',a:'spravne usuzovani',h:'Co:'},{q:'Estetika zkoumá...?',a:'krasu',h:'Co:'},{q:'Ontologie zkoumá...?',a:'bytí',h:'Co:'},{q:'Gnozeologie zkoumá...?',a:'poznavani',h:'Co:'},{q:'Empirismus vychází ze...?',a:'zkusenosti',h:'Z čeho:'},{q:'Racionalismus vychází z...?',a:'rozumu',h:'Z čeho:'},{q:'Humanismus zdůrazňuje...?',a:'cloveka',h:'Co:'},{q:'Nihilismus popírá...?',a:'hodnoty',h:'Co:'},{q:'Pragmatismus hodnotí podle...?',a:'uzitecnosti',h:'Podle čeho:'}];
DATA.ov9_etika=[{q:'Morálka = soubor...?',a:'pravidel chovani',h:'Čeho:'},{q:'Svědomí je vnitřní...?',a:'hlas',h:'Co:'},{q:'Ctnost je kladná...?',a:'vlastnost',h:'Co:'},{q:'Spravedlnost je...?',a:'rovne zachazeni',h:'Co:'},{q:'Solidarita = vzájemná...?',a:'pomoc',h:'Co:'},{q:'Empatie = schopnost...?',a:'vciteni',h:'Čeho:'},{q:'Eutanázie je eticky...? téma',a:'kontroverzni',h:'Jaké:'},{q:'Trest smrti je v ČR...?',a:'zakazan',h:'Jaký:'},{q:'Altruismus = nesobecká...?',a:'pomoc',h:'Co:'},{q:'Egoismus = sobectví',a:'sobectvi',h:'Co to je:'},{q:'Tolerance = ...?',a:'snaselivost',h:'Co:'},{q:'Diskriminace = ...?',a:'znevyhodnovani',h:'Co:'},{q:'Kodex je soubor...?',a:'pravidel',h:'Čeho:'},{q:'Etický kodex lékaře = ...?',a:'hippokratova prisaha',h:'Co:'},{q:'Dobro je opak...?',a:'zla',h:'Čeho:'}];
DATA.ov9_lidprav=[{q:'VDLP přijata roku...?',a:'1948',h:'Rok:'},{q:'VDLP = Všeobecná deklarace...?',a:'lidskych prav',h:'Čeho:'},{q:'Právo na život je právo...?',a:'zakladni',h:'Jaké:'},{q:'Otroctví je...?',a:'zakazano',h:'Jaké:'},{q:'Mučení je...?',a:'zakazano',h:'Jaké:'},{q:'Každý má právo na...? soud',a:'spravedlivy',h:'Jaký:'},{q:'Svoboda vyznání = právo na...?',a:'nabozenstvi',h:'Na co:'},{q:'Azyl = ochrana pro...?',a:'uprchliky',h:'Pro koho:'},{q:'Genocida = ...?',a:'vyhlazovani',h:'Co:'},{q:'Apartheid byl v...?',a:'jihoafricke republice',h:'Kde:'},{q:'Martin Luther King bojoval za...?',a:'rovnopravnost',h:'Za co:'},{q:'Nelson Mandela bojoval proti...?',a:'apartheidu',h:'Proti čemu:'},{q:'Humanitární právo chrání...?',a:'obeti konfliktu',h:'Koho:'},{q:'Ženevské úmluvy chrání...?',a:'valecne zajatce',h:'Koho:'},{q:'Habeas corpus chrání před...?',a:'nezakonnym uveznenim',h:'Před čím:'}];
DATA.ov9_obcprav=[{q:'Vlastnické právo = právo...?',a:'vlastnit',h:'Jaké:'},{q:'Dědické právo řeší...?',a:'dedictvi',h:'Co:'},{q:'Závěť je...?',a:'posledni vule',h:'Co:'},{q:'Kupní smlouva = smlouva o...?',a:'koupi',h:'O čem:'},{q:'Nájemní smlouva = smlouva o...?',a:'najmu',h:'O čem:'},{q:'Spotřebitel má právo na...?',a:'reklamaci',h:'Na co:'},{q:'Reklamační lhůta je...? roky',a:'2',h:'Kolik:'},{q:'Plná svéprávnost od...? let',a:'18',h:'Od kolika:'},{q:'Manželství se uzavírá na...?',a:'matrice',h:'Kde:'},{q:'Rozvod řeší...?',a:'soud',h:'Kdo:'},{q:'Výživné platí...?',a:'rodic',h:'Kdo:'},{q:'Občanský průkaz od...? let',a:'15',h:'Od kolika:'},{q:'Cestovní pas slouží k...?',a:'cestovani do zahranici',h:'K čemu:'},{q:'Autorskoprávní ochrana chrání...?',a:'dila',h:'Co:'},{q:'Patent chrání...?',a:'vynalezy',h:'Co:'}];
DATA.ov9_pracprav=[{q:'Pracovní smlouva musí být...?',a:'pisemna',h:'Jaká:'},{q:'Zkušební doba je max...? měsíce',a:'3',h:'Kolik:'},{q:'Výpovědní lhůta je...? měsíce',a:'2',h:'Kolik:'},{q:'Minimální mzda je stanovena...?',a:'zakonem',h:'Čím:'},{q:'Pracovní doba je max...? hodin/týden',a:'40',h:'Kolik:'},{q:'Dovolená je min...? týdny/rok',a:'4',h:'Kolik:'},{q:'Přesčasy jsou max...? hodin/rok',a:'150',h:'Kolik:'},{q:'BOZP = bezpečnost a ochrana...?',a:'zdravi pri praci',h:'Čeho:'},{q:'Nemocenská se vyplácí od...? dne',a:'15',h:'Od kolikátého:'},{q:'Mateřská dovolená trvá...? týdnů',a:'28',h:'Kolik:'},{q:'Pracovní úraz hlásí...?',a:'zamestnavatel',h:'Kdo:'},{q:'Odbory chrání...?',a:'zamestnance',h:'Koho:'},{q:'Brigáda na DPP = max...? hodin/rok',a:'300',h:'Kolik:'},{q:'Nezaměstnaný se eviduje na...?',a:'urade prace',h:'Kde:'},{q:'Diskriminace v práci je...?',a:'zakazana',h:'Jaká:'}];
