// ============================================
// DATA MODULE - Master index + English + Czech subjects
// ============================================

// All subjects definition
const SUBJECTS = {
    en: { name: '🇬🇧 Angličtina', color: '#00B4D8', colorLight: '#48CAE4' },
    math: { name: '🔢 Matematika', color: '#6C63FF', colorLight: '#8B83FF' },
    czech: { name: '📖 Čeština', color: '#FF6584', colorLight: '#FF8FA3' },
    civics: { name: '⚖️ Občanská výchova', color: '#F59E0B', colorLight: '#FBBF24' },
    nature: { name: '🌿 Přírodopis', color: '#10B981', colorLight: '#34D399' },
    geography: { name: '🌍 Zeměpis', color: '#8B5CF6', colorLight: '#A78BFA' },
    history: { name: '🏛️ Dějepis', color: '#EC4899', colorLight: '#F472B6' }
};

// Grade topics per subject: { subjectKey: { gradeNum: ['topicKey1', ...] } }
const GRADE_TOPICS = {};

// Topic display names: { topicKey: 'Display Name' }
const TOPIC_NAMES = {};

// All question data: { topicKey: [{q, a, h}, ...] }
const DATA = {};

// ============================================
// ENGLISH
// ============================================
GRADE_TOPICS.en = {
    '4': ['en_colors','en_numbers','en_family','en_greetings','en_school'],
    '5': ['en_house','en_clothes','en_hobbies','en_days','en_weather'],
    '6': ['en_city','en_food','en_transport','en_nature','en_body'],
    '7': ['en_sports','en_jobs','en_opposites','en_pastBe','en_prepositions'],
    '8': ['en_travel','en_shopping','en_kitchen','en_animals','en_presentCont'],
    '9': ['en_irregular','en_tech','en_eco','en_feelings','en_phrasal']
};

TOPIC_NAMES.en_colors='🎨 Barvy'; TOPIC_NAMES.en_numbers='🔢 Čísla'; TOPIC_NAMES.en_family='👨‍👩‍👧‍👦 Rodina';
TOPIC_NAMES.en_greetings='👋 Pozdravy'; TOPIC_NAMES.en_school='🏫 Škola'; TOPIC_NAMES.en_house='🏠 Dům';
TOPIC_NAMES.en_clothes='👕 Oblečení'; TOPIC_NAMES.en_hobbies='⚽ Koníčky'; TOPIC_NAMES.en_days='📅 Dny';
TOPIC_NAMES.en_weather='🌤️ Počasí'; TOPIC_NAMES.en_city='🏙️ Město'; TOPIC_NAMES.en_food='🍎 Jídlo';
TOPIC_NAMES.en_transport='🚗 Doprava'; TOPIC_NAMES.en_nature='🌳 Příroda'; TOPIC_NAMES.en_body='🦵 Tělo';
TOPIC_NAMES.en_sports='⚽ Sporty'; TOPIC_NAMES.en_jobs='👷 Povolání'; TOPIC_NAMES.en_opposites='↔️ Protiklady';
TOPIC_NAMES.en_pastBe='📝 Minulý čas BE'; TOPIC_NAMES.en_prepositions='📍 Předložky';
TOPIC_NAMES.en_travel='✈️ Cestování'; TOPIC_NAMES.en_shopping='🛒 Nakupování'; TOPIC_NAMES.en_kitchen='🍳 Kuchyně';
TOPIC_NAMES.en_animals='🦁 Zvířata'; TOPIC_NAMES.en_presentCont='📝 Přít. průběhový';
TOPIC_NAMES.en_irregular='📚 Nepravidelná slovesa'; TOPIC_NAMES.en_tech='💻 Technologie';
TOPIC_NAMES.en_eco='🌍 Ekologie'; TOPIC_NAMES.en_feelings='😊 Pocity'; TOPIC_NAMES.en_phrasal='📝 Frázová slovesa';

DATA.en_colors=[{q:'Červená',a:'red',h:'Přelož:'},{q:'Modrá',a:'blue',h:'Přelož:'},{q:'Zelená',a:'green',h:'Přelož:'},{q:'Žlutá',a:'yellow',h:'Přelož:'},{q:'Černá',a:'black',h:'Přelož:'},{q:'Bílá',a:'white',h:'Přelož:'},{q:'Hnědá',a:'brown',h:'Přelož:'},{q:'Růžová',a:'pink',h:'Přelož:'},{q:'Oranžová',a:'orange',h:'Přelož:'},{q:'Fialová',a:'purple',h:'Přelož:'},{q:'Šedá',a:'grey',h:'Přelož:'},{q:'Zlatá',a:'gold',h:'Přelož:'},{q:'Stříbrná',a:'silver',h:'Přelož:'},{q:'Světlá',a:'light',h:'Přelož:'},{q:'Tmavá',a:'dark',h:'Přelož:'}];
DATA.en_numbers=[{q:'Jedna',a:'one',h:'Přelož:'},{q:'Dva',a:'two',h:'Přelož:'},{q:'Tři',a:'three',h:'Přelož:'},{q:'Čtyři',a:'four',h:'Přelož:'},{q:'Pět',a:'five',h:'Přelož:'},{q:'Šest',a:'six',h:'Přelož:'},{q:'Sedm',a:'seven',h:'Přelož:'},{q:'Osm',a:'eight',h:'Přelož:'},{q:'Devět',a:'nine',h:'Přelož:'},{q:'Deset',a:'ten',h:'Přelož:'},{q:'Jedenáct',a:'eleven',h:'Přelož:'},{q:'Dvanáct',a:'twelve',h:'Přelož:'},{q:'Třináct',a:'thirteen',h:'Přelož:'},{q:'Čtrnáct',a:'fourteen',h:'Přelož:'},{q:'Patnáct',a:'fifteen',h:'Přelož:'}];
DATA.en_family=[{q:'Matka',a:'mother',h:'Přelož:'},{q:'Otec',a:'father',h:'Přelož:'},{q:'Sestra',a:'sister',h:'Přelož:'},{q:'Bratr',a:'brother',h:'Přelož:'},{q:'Babička',a:'grandmother',h:'Přelož:'},{q:'Dědeček',a:'grandfather',h:'Přelož:'},{q:'Syn',a:'son',h:'Přelož:'},{q:'Dcera',a:'daughter',h:'Přelož:'},{q:'Teta',a:'aunt',h:'Přelož:'},{q:'Strýc',a:'uncle',h:'Přelož:'},{q:'Bratranec',a:'cousin',h:'Přelož:'},{q:'Miminko',a:'baby',h:'Přelož:'},{q:'Rodiče',a:'parents',h:'Přelož:'},{q:'Manželka',a:'wife',h:'Přelož:'},{q:'Manžel',a:'husband',h:'Přelož:'}];
DATA.en_greetings=[{q:'Ahoj (setkání)',a:'hello',h:'Přelož:'},{q:'Ahoj (loučení)',a:'bye',h:'Přelož:'},{q:'Dobré ráno',a:'good morning',h:'Přelož:'},{q:'Dobrou noc',a:'good night',h:'Přelož:'},{q:'Prosím',a:'please',h:'Přelož:'},{q:'Děkuji',a:'thank you',h:'Přelož:'},{q:'Promiň',a:'sorry',h:'Přelož:'},{q:'Jak se máš?',a:'how are you',h:'Přelož:'},{q:'Měj se hezky',a:'have a nice day',h:'Přelož:'},{q:'Nashledanou',a:'goodbye',h:'Přelož:'},{q:'Vítejte',a:'welcome',h:'Přelož:'},{q:'Těší mě',a:'nice to meet you',h:'Přelož:'},{q:'Ano',a:'yes',h:'Přelož:'},{q:'Ne',a:'no',h:'Přelož:'},{q:'Pojď dál',a:'come in',h:'Přelož:'}];
DATA.en_school=[{q:'Škola',a:'school',h:'Přelož:'},{q:'Tužka',a:'pencil',h:'Přelož:'},{q:'Pero',a:'pen',h:'Přelož:'},{q:'Kniha',a:'book',h:'Přelož:'},{q:'Sešit',a:'notebook',h:'Přelož:'},{q:'Guma',a:'eraser',h:'Přelož:'},{q:'Pravítko',a:'ruler',h:'Přelož:'},{q:'Učitel',a:'teacher',h:'Přelož:'},{q:'Žák',a:'student',h:'Přelož:'},{q:'Tabule',a:'board',h:'Přelož:'},{q:'Třída',a:'classroom',h:'Přelož:'},{q:'Lavice',a:'desk',h:'Přelož:'},{q:'Batoh',a:'backpack',h:'Přelož:'},{q:'Papír',a:'paper',h:'Přelož:'},{q:'Ořezávátko',a:'sharpener',h:'Přelož:'}];
DATA.en_house=[{q:'Dům',a:'house',h:'Přelož:'},{q:'Pokoj',a:'room',h:'Přelož:'},{q:'Kuchyně',a:'kitchen',h:'Přelož:'},{q:'Koupelna',a:'bathroom',h:'Přelož:'},{q:'Ložnice',a:'bedroom',h:'Přelož:'},{q:'Zahrada',a:'garden',h:'Přelož:'},{q:'Okno',a:'window',h:'Přelož:'},{q:'Dveře',a:'door',h:'Přelož:'},{q:'Střecha',a:'roof',h:'Přelož:'},{q:'Zeď',a:'wall',h:'Přelož:'},{q:'Podlaha',a:'floor',h:'Přelož:'},{q:'Obývací pokoj',a:'living room',h:'Přelož:'},{q:'Garáž',a:'garage',h:'Přelož:'},{q:'Schody',a:'stairs',h:'Přelož:'},{q:'Půda',a:'attic',h:'Přelož:'}];
DATA.en_clothes=[{q:'Tričko',a:'t-shirt',h:'Přelož:'},{q:'Kalhoty',a:'trousers',h:'Přelož:'},{q:'Boty',a:'shoes',h:'Přelož:'},{q:'Bunda',a:'jacket',h:'Přelož:'},{q:'Čepice',a:'cap',h:'Přelož:'},{q:'Ponožky',a:'socks',h:'Přelož:'},{q:'Šaty',a:'dress',h:'Přelož:'},{q:'Sukně',a:'skirt',h:'Přelož:'},{q:'Svetr',a:'sweater',h:'Přelož:'},{q:'Košile',a:'shirt',h:'Přelož:'},{q:'Klobouk',a:'hat',h:'Přelož:'},{q:'Rukavice',a:'gloves',h:'Přelož:'},{q:'Brýle',a:'glasses',h:'Přelož:'},{q:'Pásek',a:'belt',h:'Přelož:'},{q:'Mikina',a:'hoodie',h:'Přelož:'}];
DATA.en_hobbies=[{q:'Hra',a:'game',h:'Přelož:'},{q:'Sport',a:'sport',h:'Přelož:'},{q:'Čtení',a:'reading',h:'Přelož:'},{q:'Psaní',a:'writing',h:'Přelož:'},{q:'Kreslení',a:'drawing',h:'Přelož:'},{q:'Zpěv',a:'singing',h:'Přelož:'},{q:'Tanec',a:'dancing',h:'Přelož:'},{q:'Plavání',a:'swimming',h:'Přelož:'},{q:'Běh',a:'running',h:'Přelož:'},{q:'Fotbal',a:'football',h:'Přelož:'},{q:'Kino',a:'cinema',h:'Přelož:'},{q:'Hudba',a:'music',h:'Přelož:'},{q:'Vaření',a:'cooking',h:'Přelož:'},{q:'Cestování',a:'travelling',h:'Přelož:'},{q:'Spaní',a:'sleeping',h:'Přelož:'}];
DATA.en_days=[{q:'Pondělí',a:'monday',h:'Přelož:'},{q:'Úterý',a:'tuesday',h:'Přelož:'},{q:'Středa',a:'wednesday',h:'Přelož:'},{q:'Čtvrtek',a:'thursday',h:'Přelož:'},{q:'Pátek',a:'friday',h:'Přelož:'},{q:'Sobota',a:'saturday',h:'Přelož:'},{q:'Neděle',a:'sunday',h:'Přelož:'},{q:'Týden',a:'week',h:'Přelož:'},{q:'Víkend',a:'weekend',h:'Přelož:'},{q:'Dnes',a:'today',h:'Přelož:'},{q:'Zítra',a:'tomorrow',h:'Přelož:'},{q:'Včera',a:'yesterday',h:'Přelož:'},{q:'Ráno',a:'morning',h:'Přelož:'},{q:'Odpoledne',a:'afternoon',h:'Přelož:'},{q:'Večer',a:'evening',h:'Přelož:'}];
DATA.en_weather=[{q:'Slunečno',a:'sunny',h:'Přelož:'},{q:'Deštivo',a:'rainy',h:'Přelož:'},{q:'Zataženo',a:'cloudy',h:'Přelož:'},{q:'Sníh',a:'snow',h:'Přelož:'},{q:'Vítr',a:'wind',h:'Přelož:'},{q:'Bouřka',a:'storm',h:'Přelož:'},{q:'Horko',a:'hot',h:'Přelož:'},{q:'Zima',a:'cold',h:'Přelož:'},{q:'Mlha',a:'fog',h:'Přelož:'},{q:'Léto',a:'summer',h:'Přelož:'},{q:'Zima (období)',a:'winter',h:'Přelož:'},{q:'Jaro',a:'spring',h:'Přelož:'},{q:'Podzim',a:'autumn',h:'Přelož:'},{q:'Duha',a:'rainbow',h:'Přelož:'},{q:'Obloha',a:'sky',h:'Přelož:'}];
DATA.en_city=[{q:'Město',a:'city',h:'Přelož:'},{q:'Ulice',a:'street',h:'Přelož:'},{q:'Obchod',a:'shop',h:'Přelož:'},{q:'Park',a:'park',h:'Přelož:'},{q:'Most',a:'bridge',h:'Přelož:'},{q:'Banka',a:'bank',h:'Přelož:'},{q:'Kino',a:'cinema',h:'Přelož:'},{q:'Muzeum',a:'museum',h:'Přelož:'},{q:'Náměstí',a:'square',h:'Přelož:'},{q:'Nemocnice',a:'hospital',h:'Přelož:'},{q:'Kostel',a:'church',h:'Přelož:'},{q:'Škola',a:'school',h:'Přelož:'},{q:'Restaurace',a:'restaurant',h:'Přelož:'},{q:'Zastávka',a:'bus stop',h:'Přelož:'},{q:'Letiště',a:'airport',h:'Přelož:'}];
DATA.en_food=[{q:'Jablko',a:'apple',h:'Přelož:'},{q:'Chleba',a:'bread',h:'Přelož:'},{q:'Mléko',a:'milk',h:'Přelož:'},{q:'Sýr',a:'cheese',h:'Přelož:'},{q:'Maso',a:'meat',h:'Přelož:'},{q:'Zelenina',a:'vegetables',h:'Přelož:'},{q:'Ovoce',a:'fruit',h:'Přelož:'},{q:'Voda',a:'water',h:'Přelož:'},{q:'Vejce',a:'egg',h:'Přelož:'},{q:'Máslo',a:'butter',h:'Přelož:'},{q:'Cukr',a:'sugar',h:'Přelož:'},{q:'Sůl',a:'salt',h:'Přelož:'},{q:'Rýže',a:'rice',h:'Přelož:'},{q:'Polévka',a:'soup',h:'Přelož:'},{q:'Džus',a:'juice',h:'Přelož:'}];
DATA.en_transport=[{q:'Auto',a:'car',h:'Přelož:'},{q:'Autobus',a:'bus',h:'Přelož:'},{q:'Vlak',a:'train',h:'Přelož:'},{q:'Kolo',a:'bike',h:'Přelož:'},{q:'Letadlo',a:'plane',h:'Přelož:'},{q:'Loď',a:'ship',h:'Přelož:'},{q:'Metro',a:'subway',h:'Přelož:'},{q:'Motorka',a:'motorbike',h:'Přelož:'},{q:'Řidič',a:'driver',h:'Přelož:'},{q:'Cesta',a:'road',h:'Přelož:'},{q:'Letět',a:'fly',h:'Přelož:'},{q:'Jet',a:'go',h:'Přelož:'},{q:'Vrtulník',a:'helicopter',h:'Přelož:'},{q:'Kamion',a:'truck',h:'Přelož:'},{q:'Taxi',a:'taxi',h:'Přelož:'}];
DATA.en_nature=[{q:'Strom',a:'tree',h:'Přelož:'},{q:'Květina',a:'flower',h:'Přelož:'},{q:'Tráva',a:'grass',h:'Přelož:'},{q:'Les',a:'forest',h:'Přelož:'},{q:'Hora',a:'mountain',h:'Přelož:'},{q:'Řeka',a:'river',h:'Přelož:'},{q:'Moře',a:'sea',h:'Přelož:'},{q:'Oceán',a:'ocean',h:'Přelož:'},{q:'Slunce',a:'sun',h:'Přelož:'},{q:'Měsíc',a:'moon',h:'Přelož:'},{q:'Hvězda',a:'star',h:'Přelož:'},{q:'Země',a:'earth',h:'Přelož:'},{q:'Ostrov',a:'island',h:'Přelož:'},{q:'Jezero',a:'lake',h:'Přelož:'},{q:'Pláž',a:'beach',h:'Přelož:'}];
DATA.en_body=[{q:'Hlava',a:'head',h:'Přelož:'},{q:'Ruka',a:'hand',h:'Přelož:'},{q:'Noha',a:'leg',h:'Přelož:'},{q:'Oko',a:'eye',h:'Přelož:'},{q:'Ucho',a:'ear',h:'Přelož:'},{q:'Nos',a:'nose',h:'Přelož:'},{q:'Ústa',a:'mouth',h:'Přelož:'},{q:'Záda',a:'back',h:'Přelož:'},{q:'Břicho',a:'stomach',h:'Přelož:'},{q:'Prst',a:'finger',h:'Přelož:'},{q:'Krk',a:'neck',h:'Přelož:'},{q:'Rameno',a:'shoulder',h:'Přelož:'},{q:'Vlasy',a:'hair',h:'Přelož:'},{q:'Zub',a:'tooth',h:'Přelož:'},{q:'Koleno',a:'knee',h:'Přelož:'}];
DATA.en_sports=[{q:'Hokej',a:'hockey',h:'Přelož:'},{q:'Tenis',a:'tennis',h:'Přelož:'},{q:'Plavání',a:'swimming',h:'Přelož:'},{q:'Lyžování',a:'skiing',h:'Přelož:'},{q:'Běh',a:'running',h:'Přelož:'},{q:'Volejbal',a:'volleyball',h:'Přelož:'},{q:'Basketbal',a:'basketball',h:'Přelož:'},{q:'Cvičení',a:'exercise',h:'Přelož:'},{q:'Tým',a:'team',h:'Přelož:'},{q:'Míč',a:'ball',h:'Přelož:'},{q:'Hráč',a:'player',h:'Přelož:'},{q:'Vyhrát',a:'win',h:'Přelož:'},{q:'Prohrát',a:'lose',h:'Přelož:'},{q:'Zápas',a:'match',h:'Přelož:'},{q:'Branka',a:'goal',h:'Přelož:'}];
DATA.en_jobs=[{q:'Doktor',a:'doctor',h:'Přelož:'},{q:'Policista',a:'policeman',h:'Přelož:'},{q:'Hasič',a:'firefighter',h:'Přelož:'},{q:'Kuchař',a:'cook',h:'Přelož:'},{q:'Řidič',a:'driver',h:'Přelož:'},{q:'Prodavač',a:'shop assistant',h:'Přelož:'},{q:'Zpěvák',a:'singer',h:'Přelož:'},{q:'Herec',a:'actor',h:'Přelož:'},{q:'Programátor',a:'programmer',h:'Přelož:'},{q:'Zdravotní sestra',a:'nurse',h:'Přelož:'},{q:'Stavitel',a:'builder',h:'Přelož:'},{q:'Zemědělec',a:'farmer',h:'Přelož:'},{q:'Úředník',a:'clerk',h:'Přelož:'},{q:'Letuška',a:'flight attendant',h:'Přelož:'},{q:'Číšník',a:'waiter',h:'Přelož:'}];
DATA.en_opposites=[{q:'Velký',a:'big',h:'Přelož:'},{q:'Malý',a:'small',h:'Přelož:'},{q:'Rychlý',a:'fast',h:'Přelož:'},{q:'Pomalý',a:'slow',h:'Přelož:'},{q:'Drahý',a:'expensive',h:'Přelož:'},{q:'Levný',a:'cheap',h:'Přelož:'},{q:'Teplý',a:'hot',h:'Přelož:'},{q:'Studený',a:'cold',h:'Přelož:'},{q:'Šťastný',a:'happy',h:'Přelož:'},{q:'Smutný',a:'sad',h:'Přelož:'},{q:'Mladý',a:'young',h:'Přelož:'},{q:'Starý',a:'old',h:'Přelož:'},{q:'Bohatý',a:'rich',h:'Přelož:'},{q:'Chudý',a:'poor',h:'Přelož:'},{q:'Krásný',a:'beautiful',h:'Přelož:'}];
DATA.en_pastBe=[{q:'Já jsem byl',a:'i was',h:'Přelož:'},{q:'Ty jsi byl',a:'you were',h:'Přelož:'},{q:'On byl',a:'he was',h:'Přelož:'},{q:'Ona byla',a:'she was',h:'Přelož:'},{q:'Ono bylo',a:'it was',h:'Přelož:'},{q:'My jsme byli',a:'we were',h:'Přelož:'},{q:'Vy jste byli',a:'you were',h:'Přelož:'},{q:'Oni byli',a:'they were',h:'Přelož:'},{q:'Nebyl jsem',a:'i was not',h:'Přelož:'},{q:'Nebyli jsme',a:'we were not',h:'Přelož:'},{q:'Byl jsi?',a:'were you',h:'Přelož:'},{q:'Byl on?',a:'was he',h:'Přelož:'},{q:'Včera',a:'yesterday',h:'Přelož:'},{q:'Minulý týden',a:'last week',h:'Přelož:'},{q:'Před dvěma dny',a:'two days ago',h:'Přelož:'}];
DATA.en_prepositions=[{q:'V',a:'in',h:'Přelož:'},{q:'Na',a:'on',h:'Přelož:'},{q:'Pod',a:'under',h:'Přelož:'},{q:'Vedle',a:'next to',h:'Přelož:'},{q:'Za',a:'behind',h:'Přelož:'},{q:'Před',a:'in front of',h:'Přelož:'},{q:'Mezi',a:'between',h:'Přelož:'},{q:'Nad',a:'above',h:'Přelož:'},{q:'U',a:'at',h:'Přelož:'},{q:'Do',a:'into',h:'Přelož:'},{q:'Z',a:'from',h:'Přelož:'},{q:'S',a:'with',h:'Přelož:'},{q:'Bez',a:'without',h:'Přelož:'},{q:'O (čem)',a:'about',h:'Přelož:'},{q:'Pro',a:'for',h:'Přelož:'}];
DATA.en_travel=[{q:'Cestovní pas',a:'passport',h:'Přelož:'},{q:'Vízum',a:'visa',h:'Přelož:'},{q:'Kufr',a:'suitcase',h:'Přelož:'},{q:'Mapa',a:'map',h:'Přelož:'},{q:'Průvodce',a:'guide',h:'Přelož:'},{q:'Dovolená',a:'holiday',h:'Přelož:'},{q:'Letenka',a:'ticket',h:'Přelož:'},{q:'Ubytování',a:'accommodation',h:'Přelož:'},{q:'Hotel',a:'hotel',h:'Přelož:'},{q:'Pláž',a:'beach',h:'Přelož:'},{q:'Památka',a:'monument',h:'Přelož:'},{q:'Zahraničí',a:'abroad',h:'Přelož:'},{q:'Výlet',a:'trip',h:'Přelož:'},{q:'Batoh',a:'backpack',h:'Přelož:'},{q:'Rezervace',a:'reservation',h:'Přelož:'}];
DATA.en_shopping=[{q:'Peníze',a:'money',h:'Přelož:'},{q:'Cena',a:'price',h:'Přelož:'},{q:'Sleva',a:'discount',h:'Přelož:'},{q:'Účtenka',a:'receipt',h:'Přelož:'},{q:'Karta',a:'card',h:'Přelož:'},{q:'Hotovost',a:'cash',h:'Přelož:'},{q:'Zákazník',a:'customer',h:'Přelož:'},{q:'Nákupní košík',a:'shopping basket',h:'Přelož:'},{q:'Trh',a:'market',h:'Přelož:'},{q:'Zkusit si',a:'try on',h:'Přelož:'},{q:'Velikost',a:'size',h:'Přelož:'},{q:'Taška',a:'bag',h:'Přelož:'},{q:'Stát (peníze)',a:'cost',h:'Přelož:'},{q:'Koupit',a:'buy',h:'Přelož:'},{q:'Prodat',a:'sell',h:'Přelož:'}];
DATA.en_kitchen=[{q:'Nůž',a:'knife',h:'Přelož:'},{q:'Vidlička',a:'fork',h:'Přelož:'},{q:'Lžíce',a:'spoon',h:'Přelož:'},{q:'Talíř',a:'plate',h:'Přelož:'},{q:'Hrnek',a:'mug',h:'Přelož:'},{q:'Sklenice',a:'glass',h:'Přelož:'},{q:'Pánev',a:'pan',h:'Přelož:'},{q:'Hrnec',a:'pot',h:'Přelož:'},{q:'Trouba',a:'oven',h:'Přelož:'},{q:'Lednice',a:'fridge',h:'Přelož:'},{q:'Mrazák',a:'freezer',h:'Přelož:'},{q:'Myčka',a:'dishwasher',h:'Přelož:'},{q:'Varná konvice',a:'kettle',h:'Přelož:'},{q:'Mísa',a:'bowl',h:'Přelož:'},{q:'Utěrka',a:'tea towel',h:'Přelož:'}];
DATA.en_animals=[{q:'Lev',a:'lion',h:'Přelož:'},{q:'Tygr',a:'tiger',h:'Přelož:'},{q:'Slon',a:'elephant',h:'Přelož:'},{q:'Žirafa',a:'giraffe',h:'Přelož:'},{q:'Zebra',a:'zebra',h:'Přelož:'},{q:'Opice',a:'monkey',h:'Přelož:'},{q:'Vlk',a:'wolf',h:'Přelož:'},{q:'Medvěd',a:'bear',h:'Přelož:'},{q:'Liška',a:'fox',h:'Přelož:'},{q:'Zajíc',a:'hare',h:'Přelož:'},{q:'Pták',a:'bird',h:'Přelož:'},{q:'Ryba',a:'fish',h:'Přelož:'},{q:'Kůň',a:'horse',h:'Přelož:'},{q:'Kráva',a:'cow',h:'Přelož:'},{q:'Prase',a:'pig',h:'Přelož:'}];
DATA.en_presentCont=[{q:'Já právě píšu',a:'i am writing',h:'Přelož:'},{q:'Ty právě jíš',a:'you are eating',h:'Přelož:'},{q:'On právě běží',a:'he is running',h:'Přelož:'},{q:'Ona právě spí',a:'she is sleeping',h:'Přelož:'},{q:'My právě hrajeme',a:'we are playing',h:'Přelož:'},{q:'Oni právě sledují',a:'they are watching',h:'Přelož:'},{q:'Já právě nejdu',a:'i am not going',h:'Přelož:'},{q:'Co právě děláš?',a:'what are you doing',h:'Přelož:'},{q:'Ona právě čte',a:'she is reading',h:'Přelož:'},{q:'Počkej',a:'wait',h:'Přelož:'},{q:'Poslouchej',a:'listen',h:'Přelož:'},{q:'Dívej se',a:'look',h:'Přelož:'},{q:'Nyní',a:'now',h:'Přelož:'},{q:'Právě teď',a:'at the moment',h:'Přelož:'},{q:'Dnes',a:'today',h:'Přelož:'}];
DATA.en_irregular=[{q:'Být (be)',a:'was been',h:'Přelož minulé tvary:'},{q:'Jít (go)',a:'went gone',h:'Přelož minulé tvary:'},{q:'Vidět (see)',a:'saw seen',h:'Přelož minulé tvary:'},{q:'Jíst (eat)',a:'ate eaten',h:'Přelož minulé tvary:'},{q:'Pít (drink)',a:'drank drunk',h:'Přelož minulé tvary:'},{q:'Dělat (do)',a:'did done',h:'Přelož minulé tvary:'},{q:'Mít (have)',a:'had had',h:'Přelož minulé tvary:'},{q:'Psát (write)',a:'wrote written',h:'Přelož minulé tvary:'},{q:'Číst (read)',a:'read read',h:'Přelož minulé tvary:'},{q:'Mluvit (speak)',a:'spoke spoken',h:'Přelož minulé tvary:'},{q:'Vzít (take)',a:'took taken',h:'Přelož minulé tvary:'},{q:'Dát (give)',a:'gave given',h:'Přelož minulé tvary:'},{q:'Koupit (buy)',a:'bought bought',h:'Přelož minulé tvary:'},{q:'Spát (sleep)',a:'slept slept',h:'Přelož minulé tvary:'},{q:'Běžet (run)',a:'ran run',h:'Přelož minulé tvary:'}];
DATA.en_tech=[{q:'Počítač',a:'computer',h:'Přelož:'},{q:'Notebook',a:'laptop',h:'Přelož:'},{q:'Klávesnice',a:'keyboard',h:'Přelož:'},{q:'Myš',a:'mouse',h:'Přelož:'},{q:'Obrazovka',a:'screen',h:'Přelož:'},{q:'Internet',a:'internet',h:'Přelož:'},{q:'Heslo',a:'password',h:'Přelož:'},{q:'Uložit',a:'save',h:'Přelož:'},{q:'Smazat',a:'delete',h:'Přelož:'},{q:'Stáhnout',a:'download',h:'Přelož:'},{q:'Nahrát',a:'upload',h:'Přelož:'},{q:'Software',a:'software',h:'Přelož:'},{q:'Aplikace',a:'application',h:'Přelož:'},{q:'Nabíječka',a:'charger',h:'Přelož:'},{q:'Sluchátka',a:'headphones',h:'Přelož:'}];
DATA.en_eco=[{q:'Životní prostředí',a:'environment',h:'Přelož:'},{q:'Znečištění',a:'pollution',h:'Přelož:'},{q:'Recyklace',a:'recycling',h:'Přelož:'},{q:'Plast',a:'plastic',h:'Přelož:'},{q:'Odpadky',a:'rubbish',h:'Přelož:'},{q:'Energie',a:'energy',h:'Přelož:'},{q:'Sluneční energie',a:'solar energy',h:'Přelož:'},{q:'Globální oteplování',a:'global warming',h:'Přelož:'},{q:'Chránit',a:'protect',h:'Přelož:'},{q:'Šetřit',a:'save',h:'Přelož:'},{q:'Příroda',a:'nature',h:'Přelož:'},{q:'Les',a:'forest',h:'Přelož:'},{q:'Vzduch',a:'air',h:'Přelož:'},{q:'Voda',a:'water',h:'Přelož:'},{q:'Zvířata',a:'animals',h:'Přelož:'}];
DATA.en_feelings=[{q:'Šťastný',a:'happy',h:'Přelož:'},{q:'Smutný',a:'sad',h:'Přelož:'},{q:'Naštvaný',a:'angry',h:'Přelož:'},{q:'Unavený',a:'tired',h:'Přelož:'},{q:'Vyděšený',a:'scared',h:'Přelož:'},{q:'Překvapený',a:'surprised',h:'Přelož:'},{q:'Nudící se',a:'bored',h:'Přelož:'},{q:'Nadšený',a:'excited',h:'Přelož:'},{q:'Nervózní',a:'nervous',h:'Přelož:'},{q:'Hrdý',a:'proud',h:'Přelož:'},{q:'Osamělý',a:'lonely',h:'Přelož:'},{q:'Zmatený',a:'confused',h:'Přelož:'},{q:'Nemocný',a:'sick',h:'Přelož:'},{q:'Hladový',a:'hungry',h:'Přelož:'},{q:'Žíznivý',a:'thirsty',h:'Přelož:'}];
DATA.en_phrasal=[{q:'Vstát',a:'get up',h:'Přelož:'},{q:'Posadit se',a:'sit down',h:'Přelož:'},{q:'Vstát (ze židle)',a:'stand up',h:'Přelož:'},{q:'Vrátit se',a:'come back',h:'Přelož:'},{q:'Pokračovat',a:'go on',h:'Přelož:'},{q:'Hledat',a:'look for',h:'Přelož:'},{q:'Vypnout',a:'turn off',h:'Přelož:'},{q:'Zapnout',a:'turn on',h:'Přelož:'},{q:'Vzdát se',a:'give up',h:'Přelož:'},{q:'Vyplnit',a:'fill in',h:'Přelož:'},{q:'Sundat si',a:'take off',h:'Přelož:'},{q:'Obléknout si',a:'put on',h:'Přelož:'},{q:'Zjistit',a:'find out',h:'Přelož:'},{q:'Vyrůstat',a:'grow up',h:'Přelož:'},{q:'Starat se o',a:'look after',h:'Přelož:'}];
