// ============================================
// NATURAL HISTORY - Přírodopis (4.-9. třída)
// ============================================

GRADE_TOPICS.nature = {
    '4': ['pr4_rostliny','pr4_zvirata','pr4_clovek','pr4_pocasi','pr4_ekosystem'],
    '5': ['pr5_lesy','pr5_voda','pr5_pole','pr5_houby','pr5_ochrana'],
    '6': ['pr6_bunka','pr6_bezobratlci','pr6_ryby','pr6_obojziv','pr6_plazi'],
    '7': ['pr7_ptaci','pr7_savci','pr7_evoluce','pr7_dedic','pr7_ekologie'],
    '8': ['pr8_telo','pr8_kostra','pr8_svaly','pr8_traveni','pr8_dychani'],
    '9': ['pr9_srdce','pr9_nervy','pr9_smysly','pr9_rozmnoz','pr9_genetika']
};

TOPIC_NAMES.pr4_rostliny='🌱 Rostliny'; TOPIC_NAMES.pr4_zvirata='🐾 Zvířata'; TOPIC_NAMES.pr4_clovek='🧑 Lidské tělo';
TOPIC_NAMES.pr4_pocasi='🌤️ Počasí a klima'; TOPIC_NAMES.pr4_ekosystem='🌳 Ekosystémy';
TOPIC_NAMES.pr5_lesy='🌲 Les'; TOPIC_NAMES.pr5_voda='💧 Voda'; TOPIC_NAMES.pr5_pole='🌾 Pole a louky';
TOPIC_NAMES.pr5_houby='🍄 Houby'; TOPIC_NAMES.pr5_ochrana='🦔 Ochrana přírody';
TOPIC_NAMES.pr6_bunka='🔬 Buňka'; TOPIC_NAMES.pr6_bezobratlci='🐛 Bezobratlí'; TOPIC_NAMES.pr6_ryby='🐟 Ryby';
TOPIC_NAMES.pr6_obojziv='🐸 Obojživelníci'; TOPIC_NAMES.pr6_plazi='🦎 Plazi';
TOPIC_NAMES.pr7_ptaci='🐦 Ptáci'; TOPIC_NAMES.pr7_savci='🐘 Savci'; TOPIC_NAMES.pr7_evoluce='🧬 Evoluce';
TOPIC_NAMES.pr7_dedic='🧬 Dědičnost'; TOPIC_NAMES.pr7_ekologie='🌍 Ekologie';
TOPIC_NAMES.pr8_telo='🧑 Soustava tělní'; TOPIC_NAMES.pr8_kostra='🦴 Kostra'; TOPIC_NAMES.pr8_svaly='💪 Svaly';
TOPIC_NAMES.pr8_traveni='🍽️ Trávení'; TOPIC_NAMES.pr8_dychani='🫁 Dýchání';
TOPIC_NAMES.pr9_srdce='❤️ Srdce a oběh'; TOPIC_NAMES.pr9_nervy='🧠 Nervová soustava'; TOPIC_NAMES.pr9_smysly='👁️ Smysly';
TOPIC_NAMES.pr9_rozmnoz='👶 Rozmnožování'; TOPIC_NAMES.pr9_genetika='🧬 Genetika';

DATA.pr4_rostliny=[{q:'Rostlina dýchá pomocí...?',a:'listu',h:'Čím:'},{q:'Fotosyntéza potřebuje...? a CO₂',a:'svetlo',h:'Co:'},{q:'Zelené barvivo v listech se nazývá...?',a:'chlorofyl',h:'Jak:'},{q:'Kořen rostliny přijímá...?',a:'vodu a ziviny',h:'Co:'},{q:'Stonek rostliny...?',a:'vede vodu',h:'Co dělá:'},{q:'Květ slouží k...?',a:'rozmnozovani',h:'K čemu:'},{q:'Plod obsahuje...?',a:'semena',h:'Co:'},{q:'Jednoletá rostlina žije...? rok',a:'jeden',h:'Kolik:'},{q:'Strom má...? kmen',a:'drevnaty',h:'Jaký:'},{q:'Keř má...? kmenů',a:'vice',h:'Kolik:'},{q:'Bylina má...? stonek',a:'bylinnaty',h:'Jaký:'},{q:'Semeno klíčí, když má...?',a:'vodu a teplo',h:'Co:'},{q:'Listy opadávají na...?',a:'podzim',h:'Kdy:'},{q:'Jehličnany mají...?',a:'jehlice',h:'Co:'},{q:'Listnaté stromy mají...?',a:'listy',h:'Co:'}];
DATA.pr4_zvirata=[{q:'Savci krmí mláďata...?',a:'mlekem',h:'Čím:'},{q:'Ptáci mají tělo pokryté...?',a:'perim',h:'Čím:'},{q:'Ryby dýchají...?',a:'zabrami',h:'Čím:'},{q:'Hmyz má...? nohou',a:'6',h:'Kolik:'},{q:'Pavouci mají...? nohou',a:'8',h:'Kolik:'},{q:'Obojživelníci žijí na souši i ve...?',a:'vode',h:'Kde:'},{q:'Plazi mají tělo pokryté...?',a:'supinami',h:'Čím:'},{q:'Domácí zvíře žije s...?',a:'clovekem',h:'S kým:'},{q:'Divoké zvíře žije ve...?',a:'volne prirode',h:'Kde:'},{q:'Býložravec jí...?',a:'rostliny',h:'Co:'},{q:'Masožravec jí...?',a:'maso',h:'Co:'},{q:'Všežravec jí...?',a:'vse',h:'Co:'},{q:'Hibernace = zimní...?',a:'spanek',h:'Co:'},{q:'Migrace = stěhování...?',a:'zvirat',h:'Čeho:'},{q:'Metamorfóza = proměna...?',a:'tvaru',h:'Čeho:'}];
DATA.pr4_clovek=[{q:'Srdce pumpuje...?',a:'krev',h:'Co:'},{q:'Plíce slouží k...?',a:'dychani',h:'K čemu:'},{q:'Mozek řídí...?',a:'telo',h:'Co:'},{q:'Žaludek tráví...?',a:'jidlo',h:'Co:'},{q:'Kostra chrání...?',a:'vnitrni organy',h:'Co:'},{q:'Kůže chrání tělo před...?',a:'infekcemi',h:'Před čím:'},{q:'Oko slouží k...?',a:'videni',h:'K čemu:'},{q:'Ucho slouží k...?',a:'slysen',h:'K čemu:'},{q:'Nos slouží k...?',a:'cichani',h:'K čemu:'},{q:'Jazyk slouží k...?',a:'chutnan',h:'K čemu:'},{q:'Kolik kostí má dospělý člověk (cca)?',a:'206',h:'Kolik:'},{q:'Krev je...? barvy',a:'cervene',h:'Jaké:'},{q:'Zuby slouží k...?',a:'kousani',h:'K čemu:'},{q:'Svaly umožňují...?',a:'pohyb',h:'Co:'},{q:'Vitamíny jsou důležité pro...?',a:'zdravi',h:'Pro co:'}];
DATA.pr4_pocasi=[{q:'Teplotu měříme...?',a:'teplomerem',h:'Čím:'},{q:'Srážky měříme...?',a:'srazkomerem',h:'Čím:'},{q:'Vítr měříme...?',a:'vetromerem',h:'Čím:'},{q:'Kolik ročních období je?',a:'4',h:'Kolik:'},{q:'Nejkratší den je v...?',a:'prosinci',h:'Kdy:'},{q:'Nejdelší den je v...?',a:'cervnu',h:'Kdy:'},{q:'Oblaky jsou tvořeny z...?',a:'vodnich kapek',h:'Z čeho:'},{q:'Duha vzniká po...?',a:'desti',h:'Po čem:'},{q:'Blesk je elektrický...?',a:'vyboj',h:'Co:'},{q:'Sníh padá při teplotě pod...? °C',a:'0',h:'Kolik:'},{q:'Podnebí = dlouhodobé...?',a:'pocasi',h:'Co:'},{q:'Počasí se mění...?',a:'denne',h:'Jak často:'},{q:'Meteorolog předpovídá...?',a:'pocasi',h:'Co:'},{q:'Barometr měří...?',a:'tlak vzduchu',h:'Co:'},{q:'Mlha je nízký...?',a:'oblak',h:'Co:'}];
DATA.pr4_ekosystem=[{q:'Ekosystém = společenstvo organismů a...?',a:'prostredi',h:'A co:'},{q:'Les je...? ekosystém',a:'suchozemsky',h:'Jaký:'},{q:'Jezero je...? ekosystém',a:'sladkovodni',h:'Jaký:'},{q:'Potravinový řetězec začíná...?',a:'rostlinou',h:'Čím:'},{q:'Producent v řetězci je...?',a:'rostlina',h:'Co:'},{q:'Konzument je...?',a:'zvire',h:'Co:'},{q:'Rozkladač je...?',a:'bakterie houba',h:'Co:'},{q:'Kyslík vyrábějí...?',a:'rostliny',h:'Co:'},{q:'CO₂ produkují...?',a:'zvirata',h:'Co:'},{q:'Biom = velký...?',a:'ekosystem',h:'Co:'},{q:'Tundra je v...? oblastech',a:'arktickych',h:'V jakých:'},{q:'Savana je v...?',a:'africe',h:'Kde:'},{q:'Deštný prales je v...?',a:'tropech',h:'Kde:'},{q:'Pouště mají málo...?',a:'vody',h:'Čeho:'},{q:'Mokřad je přechod mezi souší a...?',a:'vodou',h:'Čím:'}];

DATA.pr5_lesy=[{q:'Smrk je...? strom',a:'jehlicnaty',h:'Jaký:'},{q:'Dub je...? strom',a:'listnaty',h:'Jaký:'},{q:'Lesní patro: stromy, keře, byliny,...?',a:'mechy',h:'A co:'},{q:'Liška je...? zvíře',a:'masozrave',h:'Jaké:'},{q:'Srnec je...? zvíře',a:'bylozrave',h:'Jaké:'},{q:'Datel hledá hmyz v...?',a:'kure stromu',h:'Kde:'},{q:'Les produkuje...?',a:'kyslik',h:'Co:'},{q:'Lišejník je spojení houby a...?',a:'rasy',h:'A čeho:'},{q:'Jehličnatý les = ...?',a:'tajga',h:'Jak se nazývá:'},{q:'Smíšený les má jehličnany i...?',a:'listane',h:'A co:'},{q:'Kůrovec je škůdce...?',a:'smrku',h:'Čeho:'},{q:'Mech roste na...? straně kamene',a:'severni',h:'Na jaké:'},{q:'Les chrání půdu před...?',a:'erozi',h:'Před čím:'},{q:'Myslivec se stará o...?',a:'zver',h:'O co:'},{q:'Paseka je místo po...?',a:'vykacer lese',h:'Po čem:'}];
DATA.pr5_voda=[{q:'Koloběh vody: odpařování → srážky →...?',a:'odtok',h:'A co:'},{q:'Sladká voda tvoří...? % vody na Zemi',a:'3',h:'Kolik (cca):'},{q:'Nejvíce vody na Zemi je...?',a:'slana',h:'Jaká:'},{q:'Řeka teče do...?',a:'more',h:'Kam:'},{q:'Pramen = místo kde voda...?',a:'vyvera',h:'Co:'},{q:'Podzemní voda se nazývá...?',a:'podzemni',h:'Jak:'},{q:'Ledovec je zmrzlá...?',a:'voda',h:'Co:'},{q:'Rybník je...? vodní nádrž',a:'umela',h:'Jaká:'},{q:'Jezero je...? vodní nádrž',a:'prirozena',h:'Jaká:'},{q:'Plankton jsou drobné...?',a:'organismy',h:'Co:'},{q:'Vodní rostlina leknín roste na...?',a:'hladine',h:'Kde:'},{q:'Žába je...?',a:'obojzivelnik',h:'Co:'},{q:'Vydra žije u...?',a:'vody',h:'Kde:'},{q:'Čistírna odpadních vod čistí...?',a:'odpadni vodu',h:'Co:'},{q:'Voda se vaří při...? °C',a:'100',h:'Kolik:'}];
DATA.pr5_pole=[{q:'Pšenice se pěstuje pro...?',a:'mouku',h:'Pro co:'},{q:'Kukuřice pochází z...?',a:'ameriky',h:'Odkud:'},{q:'Brambory obsahují...?',a:'skrob',h:'Co:'},{q:'Řepka se pěstuje pro...?',a:'olej',h:'Pro co:'},{q:'Cukrovka se pěstuje pro...?',a:'cukr',h:'Pro co:'},{q:'Chmel se používá na...?',a:'pivo',h:'Na co:'},{q:'Vinice je pole s...?',a:'vinnou revou',h:'S čím:'},{q:'Slunečnice se pěstuje pro...?',a:'olej a semena',h:'Pro co:'},{q:'Včely opylují...?',a:'kvety',h:'Co:'},{q:'Obilniny jsou: pšenice, žito,...?',a:'jecmen oves',h:'A co:'},{q:'Luční květ kopretina je...? barvy',a:'bile',h:'Jaké:'},{q:'Motýl se živí...?',a:'nektarem',h:'Čím:'},{q:'Krtek žije...?',a:'pod zemi',h:'Kde:'},{q:'Zajíc polní žije na...?',a:'polich',h:'Kde:'},{q:'Pesticidy hubí...?',a:'skudce',h:'Co:'}];
DATA.pr5_houby=[{q:'Hřib dubový je...? houba',a:'jedla',h:'Jaká:'},{q:'Muchomůrka červená je...?',a:'jedovata',h:'Jaká:'},{q:'Houby nemají...?',a:'chlorofyl',h:'Co:'},{q:'Houby jsou...? (rostlina/živočich/ani)',a:'ani',h:'Co:'},{q:'Podhoubí = ...?',a:'mycelium',h:'Jak se nazývá:'},{q:'Klobouk houby nese...?',a:'vyrtusy',h:'Co:'},{q:'Plísně jsou...?',a:'houby',h:'Co:'},{q:'Kvasnice jsou...?',a:'houby',h:'Co:'},{q:'Penicilín se získává z...?',a:'plisne',h:'Z čeho:'},{q:'Symbioza houby a stromu = ...?',a:'mykorhiza',h:'Jak:'},{q:'Lišky jsou...? barvy',a:'zlute',h:'Jaké:'},{q:'Ryzec je jedlá houba...? barvy',a:'oranzove',h:'Jaké:'},{q:'Muchomůrka zelená je...?',a:'smrtelne jedovata',h:'Jaká:'},{q:'Houby sbíráme do...?',a:'kosiku',h:'Do čeho:'},{q:'Nejistou houbu...?',a:'nebereme',h:'Co s ní:'}];
DATA.pr5_ochrana=[{q:'Národní park chrání...?',a:'prirodu',h:'Co:'},{q:'CHKO = chráněná krajinná...?',a:'oblast',h:'Co:'},{q:'Červená kniha obsahuje...?',a:'ohrozene druhy',h:'Co:'},{q:'NP Šumava je na...?',a:'sumave',h:'Kde:'},{q:'NP Krkonoše chrání...?',a:'hory',h:'Co:'},{q:'Třídění odpadu = ...?',a:'recyklace',h:'Co:'},{q:'Žlutý kontejner je na...?',a:'plast',h:'Na co:'},{q:'Modrý kontejner je na...?',a:'papir',h:'Na co:'},{q:'Zelený kontejner je na...?',a:'sklo',h:'Na co:'},{q:'Kompostování rozloží...?',a:'bioodpad',h:'Co:'},{q:'Ozonová díra propouští...?',a:'uv zareni',h:'Co:'},{q:'Skleníkový efekt otepluje...?',a:'planetu',h:'Co:'},{q:'Kyselý déšť poškozuje...?',a:'lesy',h:'Co:'},{q:'Endangered species = ...?',a:'ohrozene druhy',h:'Co:'},{q:'Biodiverzita = rozmanitost...?',a:'zivota',h:'Čeho:'}];

DATA.pr6_bunka=[{q:'Buňka je základní jednotka...?',a:'zivota',h:'Čeho:'},{q:'Jádro buňky obsahuje...?',a:'dna',h:'Co:'},{q:'Buněčná membrána obaluje...?',a:'bunku',h:'Co:'},{q:'Cytoplazma vyplňuje...?',a:'bunku',h:'Co:'},{q:'Chloroplast provádí...?',a:'fotosyntezu',h:'Co:'},{q:'Mitochondrie vyrábí...?',a:'energii',h:'Co:'},{q:'Rostlinná buňka má navíc...?',a:'bunecnou stenu',h:'Co:'},{q:'Živočišná buňka nemá...?',a:'bunecnou stenu',h:'Co:'},{q:'Dělení buňky = ...?',a:'mitoza',h:'Jak:'},{q:'Tkáň = skupina stejných...?',a:'bunek',h:'Čeho:'},{q:'Orgán = skupina...?',a:'tkani',h:'Čeho:'},{q:'Organismus = celek...?',a:'organu',h:'Čeho:'},{q:'DNA je nositel...?',a:'dedicne informace',h:'Čeho:'},{q:'Chromosom obsahuje...?',a:'dna',h:'Co:'},{q:'Mikroskop zvětšuje...?',a:'obrazy',h:'Co:'}];
DATA.pr6_bezobratlci=[{q:'Hmyz má...? částí těla',a:'3',h:'Kolik:'},{q:'Červi nemají...?',a:'kostru',h:'Co:'},{q:'Žížala žije v...?',a:'pude',h:'Kde:'},{q:'Měkkýši mají...?',a:'mekke telo',h:'Co:'},{q:'Hlemýžď má...?',a:'ulitu',h:'Co:'},{q:'Korýši dýchají...?',a:'zabrami',h:'Čím:'},{q:'Rak je...?',a:'korys',h:'Co:'},{q:'Pavouk má...? nohou',a:'8',h:'Kolik:'},{q:'Klíště je...?',a:'parazit',h:'Co:'},{q:'Včela produkuje...?',a:'med',h:'Co:'},{q:'Motýl prochází...?',a:'premenu',h:'Čím:'},{q:'Housenka je larva...?',a:'motyla',h:'Čeho:'},{q:'Mravenci žijí v...?',a:'mravenosti',h:'Kde:'},{q:'Medúza žije v...?',a:'mori',h:'Kde:'},{q:'Korál tvoří...?',a:'utesy',h:'Co:'}];
DATA.pr6_ryby=[{q:'Ryby dýchají...?',a:'zabrami',h:'Čím:'},{q:'Ryby mají tělo pokryté...?',a:'supinami',h:'Čím:'},{q:'Ploutve slouží k...?',a:'plavani',h:'K čemu:'},{q:'Kapr je...? ryba',a:'sladkovodni',h:'Jaká:'},{q:'Žralok je...? ryba',a:'morska',h:'Jaká:'},{q:'Pstruh žije v...? vodě',a:'ciste',h:'V jaké:'},{q:'Losos migruje z moře do...?',a:'reky',h:'Kam:'},{q:'Ryby jsou...? (teplokrevné/studenokrevné)',a:'studenokrevne',h:'Jaké:'},{q:'Boční čára u ryb slouží k...?',a:'vnimani proudu',h:'K čemu:'},{q:'Plovací měchýř pomáhá rybě...?',a:'vznase se',h:'Co:'},{q:'Jikry jsou...?',a:'rybi vajicka',h:'Co:'},{q:'Úhoř je...? tvaru',a:'hadoviteho',h:'Jakého:'},{q:'Štika je...?',a:'dravec',h:'Co:'},{q:'Sumec je největší...? ryba u nás',a:'sladkovodni',h:'Jaká:'},{q:'Candát žije v...?',a:'rece',h:'Kde:'}];
DATA.pr6_obojziv=[{q:'Obojživelníci žijí na souši i ve...?',a:'vode',h:'Kde:'},{q:'Žába dýchá plícemi a...?',a:'kuzi',h:'Čím:'},{q:'Pulec je larva...?',a:'zaby',h:'Čeho:'},{q:'Pulec dýchá...?',a:'zabrami',h:'Čím:'},{q:'Metamorfóza pulce = proměna v...?',a:'zabu',h:'V co:'},{q:'Skokan je druh...?',a:'zaby',h:'Čeho:'},{q:'Čolek žije u...?',a:'vody',h:'Kde:'},{q:'Mlok skvrnitý je...? barvy',a:'zluto cerne',h:'Jaké:'},{q:'Ropucha má...? kůži',a:'bradavicnatou',h:'Jakou:'},{q:'Obojživelníci jsou...?',a:'studenokrevni',h:'Jací:'},{q:'Rosnička je...? barvy',a:'zelene',h:'Jaké:'},{q:'Obojživelníci se rozmnožují ve...?',a:'vode',h:'Kde:'},{q:'Kuňka vydává zvuk...?',a:'kun kun',h:'Jaký:'},{q:'Žába loví hmyz...?',a:'jazykem',h:'Čím:'},{q:'Obojživelníci hibernují v...?',a:'zime',h:'Kdy:'}];
DATA.pr6_plazi=[{q:'Plazi mají tělo pokryté...?',a:'supinami',h:'Čím:'},{q:'Plazi jsou...?',a:'studenokrevni',h:'Jací:'},{q:'Had nemá...?',a:'koncetiny',h:'Co:'},{q:'Ještěrka je...?',a:'plaz',h:'Co:'},{q:'Želva má...?',a:'krunyr',h:'Co:'},{q:'Krokodýl žije u...?',a:'vody',h:'Kde:'},{q:'Zmije obecná je...? had u nás',a:'jedovaty',h:'Jaký:'},{q:'Užovka je...? had',a:'nejedovaty',h:'Jaký:'},{q:'Plazi se rozmnožují...?',a:'vajicky',h:'Čím:'},{q:'Chameleon mění...?',a:'barvu',h:'Co:'},{q:'Gekoni mají přísavky na...?',a:'nohach',h:'Kde:'},{q:'Leguán je druh...?',a:'ještěra',h:'Čeho:'},{q:'Kobra je...? had',a:'jedovaty',h:'Jaký:'},{q:'Dinosauři byli...?',a:'plazi',h:'Co:'},{q:'Slepýš je...? (had/ještěrka)',a:'jesterka',h:'Co:'}];

DATA.pr7_ptaci=[{q:'Ptáci mají tělo pokryté...?',a:'perim',h:'Čím:'},{q:'Ptáci jsou...? (teplokrevní/studenokrevní)',a:'teplokrevni',h:'Jací:'},{q:'Ptáci se rozmnožují...?',a:'vajicky',h:'Čím:'},{q:'Orel je...?',a:'dravec',h:'Co:'},{q:'Vlaštovka je...? pták',a:'stehovavy',h:'Jaký:'},{q:'Kos je...? pták',a:'zpevny',h:'Jaký:'},{q:'Sova loví v...?',a:'noci',h:'Kdy:'},{q:'Tučňák žije na...?',a:'antarktide',h:'Kde:'},{q:'Pelikán má...?',a:'vak pod zobákem',h:'Co:'},{q:'Datel hledá hmyz v...?',a:'dreve',h:'Kde:'},{q:'Pštros je největší...?',a:'ptak',h:'Co:'},{q:'Kolibřík je nejmenší...?',a:'ptak',h:'Co:'},{q:'Křídla slouží k...?',a:'letu',h:'K čemu:'},{q:'Zobák slouží k...?',a:'krmeni',h:'K čemu:'},{q:'Hnízdo slouží k...?',a:'hnizdeni',h:'K čemu:'}];
DATA.pr7_savci=[{q:'Savci krmí mláďata...?',a:'mlekem',h:'Čím:'},{q:'Savci jsou...?',a:'teplokrevni',h:'Jací:'},{q:'Velryba je...?',a:'savec',h:'Co:'},{q:'Netopýr je...? savec',a:'letajici',h:'Jaký:'},{q:'Klokan má...?',a:'vak',h:'Co:'},{q:'Ptakopysk snáší...?',a:'vajicka',h:'Co:'},{q:'Šelma je...? savec',a:'masozravy',h:'Jaký:'},{q:'Primáti zahrnují opice a...?',a:'cloveka',h:'A koho:'},{q:'Slon je největší...? savec',a:'suchozemsky',h:'Jaký:'},{q:'Velryba modrá je největší...?',a:'zivocich',h:'Co:'},{q:'Gepard je nejrychlejší...?',a:'suchozemske zvire',h:'Co:'},{q:'Hibernace = zimní...?',a:'spanek',h:'Co:'},{q:'Hlodavci mají stále rostoucí...?',a:'zuby',h:'Co:'},{q:'Kopytníci mají...?',a:'kopyta',h:'Co:'},{q:'Šelmy mají ostré...?',a:'tesaky',h:'Co:'}];
DATA.pr7_evoluce=[{q:'Charles Darwin napsal „O původu..."',a:'druhu',h:'Doplň:'},{q:'Evoluce = ...?',a:'vyvoj druhu',h:'Co:'},{q:'Přirozený výběr = přežijí...?',a:'nejprizpusobivejsi',h:'Kdo:'},{q:'Fosilie jsou...?',a:'zkameneliny',h:'Co:'},{q:'Dinosauři vyhynuli před...? mil. let',a:'66',h:'Kolik:'},{q:'Člověk a opice mají společného...?',a:'predka',h:'Co:'},{q:'Homo sapiens = ...?',a:'clovek moudy',h:'Co:'},{q:'Mutace je změna v...?',a:'dna',h:'V čem:'},{q:'Adaptace = přizpůsobení...?',a:'prostredi',h:'Čemu:'},{q:'Druh = skupina org. schopných...?',a:'rozmnozovani',h:'Čeho:'},{q:'Paleontologie studuje...?',a:'fosilie',h:'Co:'},{q:'Vymírání druhů je...? proces',a:'prirozeny',h:'Jaký:'},{q:'Věk Země je asi...? mld let',a:'4.5',h:'Kolik:'},{q:'První život vznikl ve...?',a:'vode',h:'Kde:'},{q:'Pangea byla...?',a:'prakontinent',h:'Co:'}];
DATA.pr7_dedic=[{q:'DNA je zkratka pro...?',a:'deoxyribonukleova kyselina',h:'Co:'},{q:'Gen je úsek...?',a:'dna',h:'Čeho:'},{q:'Chromosom je v...?',a:'jadru bunky',h:'Kde:'},{q:'Člověk má...? párů chromosomů',a:'23',h:'Kolik:'},{q:'XX chromosomy = ...?',a:'zena',h:'Kdo:'},{q:'XY chromosomy = ...?',a:'muz',h:'Kdo:'},{q:'Dominantní gen se projeví...?',a:'vzdy',h:'Kdy:'},{q:'Recesivní gen se projeví pokud je...?',a:'v obou kopiich',h:'Kdy:'},{q:'Mendel zkoumal dědičnost na...?',a:'hrachu',h:'Na čem:'},{q:'Genotyp = soubor...?',a:'genu',h:'Čeho:'},{q:'Fenotyp = vnější...?',a:'projev genu',h:'Co:'},{q:'Kříženec = potomek...?',a:'ruznych rodicu',h:'Koho:'},{q:'Dědičná nemoc se přenáší přes...?',a:'geny',h:'Přes co:'},{q:'Klonování = vytvoření...?',a:'geneticke kopie',h:'Čeho:'},{q:'GMO = geneticky modifikovaný...?',a:'organismus',h:'Co:'}];
DATA.pr7_ekologie=[{q:'Ekologie studuje vztahy org. a...?',a:'prostredi',h:'A čeho:'},{q:'Populace = skupina jednoho...?',a:'druhu',h:'Čeho:'},{q:'Biotop = prostředí pro...?',a:'organismy',h:'Pro co:'},{q:'Producent = ...?',a:'rostlina',h:'Co:'},{q:'Konzument 1. řádu = ...?',a:'bylozravec',h:'Co:'},{q:'Konzument 2. řádu = ...?',a:'masozravec',h:'Co:'},{q:'Dekompozitor = ...?',a:'rozkladac',h:'Co:'},{q:'Symbióza = vzájemně...?',a:'prospesny vztah',h:'Jaký:'},{q:'Parazitismus = ...?',a:'prizivnictvi',h:'Co:'},{q:'Predace = ...?',a:'loveni',h:'Co:'},{q:'Potravní pyramida má na vrchu...?',a:'predatora',h:'Koho:'},{q:'Uhlíkový cyklus zahrnuje CO₂ a...?',a:'kyslik',h:'A co:'},{q:'Eutrofizace je nadměrný růst řas v...?',a:'vode',h:'Kde:'},{q:'Invazní druh ohrožuje...?',a:'puvodni druhy',h:'Co:'},{q:'Biodiverzita = rozmanitost...?',a:'druhu',h:'Čeho:'}];

DATA.pr8_telo=[{q:'Kolik orgánových soustav má člověk?',a:'11',h:'Kolik (cca):'},{q:'Oběhová soustava = srdce a...?',a:'cevy',h:'A co:'},{q:'Dýchací soustava = plíce a...?',a:'dychaci cesty',h:'A co:'},{q:'Trávicí soustava začíná...?',a:'usty',h:'Čím:'},{q:'Vylučovací soustava = ledviny a...?',a:'mocove cesty',h:'A co:'},{q:'Nervová soustava = mozek a...?',a:'nervy',h:'A co:'},{q:'Endokrinní soustava = ...?',a:'zlazy',h:'Co:'},{q:'Pohybová soustava = kostra a...?',a:'svaly',h:'A co:'},{q:'Kožní soustava chrání...?',a:'telo',h:'Co:'},{q:'Imunitní soustava bojuje s...?',a:'infekcemi',h:'S čím:'},{q:'Reprodukční soustava slouží k...?',a:'rozmnozovani',h:'K čemu:'},{q:'Lymfatický systém odvádí...?',a:'lymfu',h:'Co:'},{q:'Homeostáze = udržení stálého...?',a:'vnitrniho prostredi',h:'Čeho:'},{q:'Hormon je chemický...?',a:'posel',h:'Co:'},{q:'Inzulín reguluje hladinu...?',a:'cukru',h:'Čeho:'}];
DATA.pr8_kostra=[{q:'Kostra dospělého má...? kostí (cca)',a:'206',h:'Kolik:'},{q:'Lebka chrání...?',a:'mozek',h:'Co:'},{q:'Páteř má...? obratlů (cca)',a:'33',h:'Kolik:'},{q:'Žebra chrání...?',a:'plice a srdce',h:'Co:'},{q:'Kolik párů žeber má člověk?',a:'12',h:'Kolik:'},{q:'Stehenní kost je...? kost v těle',a:'nejdelsi',h:'Jaká:'},{q:'Kloub spojuje dvě...?',a:'kosti',h:'Co:'},{q:'Chrupavka tlumí...?',a:'narazy',h:'Co:'},{q:'Kostní dřeň tvoří...?',a:'krvniky',h:'Co:'},{q:'Vápník posiluje...?',a:'kosti',h:'Co:'},{q:'Zlomenina = ...?',a:'praskla kost',h:'Co:'},{q:'Pánev chrání...?',a:'vnitrni organy',h:'Co:'},{q:'Lopatka je na...?',a:'zadech',h:'Kde:'},{q:'Klíční kost spojuje rameno s...?',a:'hrudnikem',h:'S čím:'},{q:'Kostra novorozence má více...?',a:'chrupavek',h:'Čeho:'}];
DATA.pr8_svaly=[{q:'Kolik svalů má lidské tělo (cca)?',a:'600',h:'Kolik:'},{q:'Kosterní sval je...? (vůlí/bez vůle)',a:'ovladany vuli',h:'Jaký:'},{q:'Srdeční sval pracuje...?',a:'bez vule',h:'Jak:'},{q:'Hladký sval je ve stěnách...?',a:'organu',h:'Čeho:'},{q:'Biceps je sval na...?',a:'pazi',h:'Kde:'},{q:'Triceps je sval na zadní straně...?',a:'paze',h:'Čeho:'},{q:'Sval se zkracuje = ...?',a:'stahuje',h:'Co dělá:'},{q:'Svaly potřebují...? k práci',a:'energii',h:'Co:'},{q:'Kyselina mléčná vzniká při...?',a:'namaze',h:'Při čem:'},{q:'Bránice odděluje hrudník od...?',a:'brisis',h:'Od čeho:'},{q:'Šlacha připojuje sval ke...?',a:'kosti',h:'K čemu:'},{q:'Mimické svaly jsou na...?',a:'obliceji',h:'Kde:'},{q:'Lýtkový sval je na...?',a:'noze',h:'Kde:'},{q:'Křeč = nechtěné stažení...?',a:'svalu',h:'Čeho:'},{q:'Sval roste při...?',a:'cviceni',h:'Při čem:'}];
DATA.pr8_traveni=[{q:'Trávení začíná v...?',a:'ustech',h:'Kde:'},{q:'Sliny obsahují enzym...?',a:'amylazu',h:'Jaký:'},{q:'Jícen vede potravu do...?',a:'zaludku',h:'Kam:'},{q:'Žaludek obsahuje...? kyselinu',a:'solnou',h:'Jakou:'},{q:'Tenké střevo vstřebává...?',a:'ziviny',h:'Co:'},{q:'Tlusté střevo vstřebává...?',a:'vodu',h:'Co:'},{q:'Játra produkují...?',a:'zluc',h:'Co:'},{q:'Slinivka produkuje...?',a:'inzulin',h:'Co:'},{q:'Slepé střevo je slepý výběžek...?',a:'tlusteho streva',h:'Čeho:'},{q:'Kolik zubů má dospělý?',a:'32',h:'Kolik:'},{q:'Řezáky slouží k...?',a:'kousani',h:'K čemu:'},{q:'Stoličky slouží k...?',a:'mleti',h:'K čemu:'},{q:'Peristaltika = pohyb...?',a:'strevni steny',h:'Čeho:'},{q:'Vitamíny se vstřebávají v...?',a:'tenkem streve',h:'Kde:'},{q:'Vláknina podporuje...?',a:'traveni',h:'Co:'}];
DATA.pr8_dychani=[{q:'Plíce jsou v...?',a:'hrudniku',h:'Kde:'},{q:'Vdechujeme...?',a:'kyslik',h:'Co:'},{q:'Vydechujeme...?',a:'co2',h:'Co:'},{q:'Průdušky vedou vzduch do...?',a:'plic',h:'Kam:'},{q:'Plicní sklípky = ...?',a:'alveoly',h:'Jak:'},{q:'V alveolech probíhá výměna...?',a:'plynu',h:'Čeho:'},{q:'Bránice je sval pod...?',a:'plicemi',h:'Pod čím:'},{q:'Dýchání řídí...?',a:'mozek',h:'Co:'},{q:'Kašel je obranný...?',a:'reflex',h:'Co:'},{q:'Nos filtruje...?',a:'vzduch',h:'Co:'},{q:'Hlasivky jsou v...?',a:'hrtanu',h:'Kde:'},{q:'Astma postihuje...?',a:'prdusky',h:'Co:'},{q:'Frekvence dýchání: cca...? dechů/min',a:'16',h:'Kolik:'},{q:'Pneumonie = zápal...?',a:'plic',h:'Čeho:'},{q:'Kouření poškozuje...?',a:'plice',h:'Co:'}];

DATA.pr9_srdce=[{q:'Srdce má...? komory',a:'4',h:'Kolik:'},{q:'Tepny vedou krev...? od srdce',a:'od',h:'Odkud:'},{q:'Žíly vedou krev...? k srdci',a:'k',h:'Kam:'},{q:'Červené krvinky přenášejí...?',a:'kyslik',h:'Co:'},{q:'Bílé krvinky bojují s...?',a:'infekcemi',h:'S čím:'},{q:'Krevní destičky zajišťují...?',a:'srazeni krve',h:'Co:'},{q:'Plazma je tekutá část...?',a:'krve',h:'Čeho:'},{q:'Krevní tlak měříme...?',a:'tonometrem',h:'Čím:'},{q:'Tep = počet tepů za...?',a:'minutu',h:'Za co:'},{q:'Normální tep: cca...? tepů/min',a:'70',h:'Kolik:'},{q:'Aorta je největší...?',a:'tepna',h:'Co:'},{q:'Malý krevní oběh vede do...?',a:'plic',h:'Kam:'},{q:'Velký krevní oběh vede do...?',a:'tela',h:'Kam:'},{q:'Krevní skupiny: A, B, AB,...?',a:'0',h:'A jaká:'},{q:'Infarkt = ucpání...?',a:'vencite tepny',h:'Čeho:'}];
DATA.pr9_nervy=[{q:'Mozek je v...?',a:'lebce',h:'Kde:'},{q:'Mícha je v...?',a:'pateri',h:'Kde:'},{q:'Neuron je...?',a:'nervova bunka',h:'Co:'},{q:'Synapse spojuje dva...?',a:'neurony',h:'Co:'},{q:'Velký mozek řídí...?',a:'mysleni',h:'Co:'},{q:'Mozeček řídí...?',a:'rovnovahu',h:'Co:'},{q:'Prodloužená mícha řídí...?',a:'dychani a srdce',h:'Co:'},{q:'Reflex je automatická...?',a:'reakce',h:'Co:'},{q:'Periferní nervy vedou signály z...?',a:'tela',h:'Odkud:'},{q:'Bolest je...? signál',a:'varovny',h:'Jaký:'},{q:'Anestezie potlačuje...?',a:'bolest',h:'Co:'},{q:'Melatonin reguluje...?',a:'spanek',h:'Co:'},{q:'Adrenalin se uvolňuje při...?',a:'stresu',h:'Při čem:'},{q:'Endorfiny vyvolávají pocit...?',a:'stesti',h:'Čeho:'},{q:'Epilepsie postihuje...?',a:'mozek',h:'Co:'}];
DATA.pr9_smysly=[{q:'Kolik základních smyslů má člověk?',a:'5',h:'Kolik:'},{q:'Sítnice oka zachycuje...?',a:'svetlo',h:'Co:'},{q:'Čočka oka zaostřuje...?',a:'obraz',h:'Co:'},{q:'Zornice reguluje množství...?',a:'svetla',h:'Čeho:'},{q:'Krátkozrakost = špatně vidí do...?',a:'dalky',h:'Kam:'},{q:'Dalekozrakost = špatně vidí do...?',a:'blizka',h:'Kam:'},{q:'Bubeníček v uchu vibruje od...?',a:'zvuku',h:'Od čeho:'},{q:'Hlemýžď v uchu vnímá...?',a:'zvuk',h:'Co:'},{q:'Rovnovážné ústrojí je ve...?',a:'vnitrnim uchu',h:'Kde:'},{q:'Chuťové pohárky jsou na...?',a:'jazyku',h:'Kde:'},{q:'Čichové buňky jsou v...?',a:'nose',h:'Kde:'},{q:'Hmat vnímáme...?',a:'kuzi',h:'Čím:'},{q:'Bolest vnímají...?',a:'nervova zakonceni',h:'Co:'},{q:'Decibel měří hlasitost...?',a:'zvuku',h:'Čeho:'},{q:'Slepota = ztráta...?',a:'zraku',h:'Čeho:'}];
DATA.pr9_rozmnoz=[{q:'Pohlavní buňka muže = ...?',a:'spermie',h:'Co:'},{q:'Pohlavní buňka ženy = ...?',a:'vajicko',h:'Co:'},{q:'Oplodnění = spojení spermie a...?',a:'vajicka',h:'A čeho:'},{q:'Těhotenství trvá...? měsíců',a:'9',h:'Kolik:'},{q:'Placenta vyživuje...?',a:'plod',h:'Co:'},{q:'Pubescentní období = ...?',a:'dospivani',h:'Co:'},{q:'Menstruace je součástí cyklu...?',a:'zenského',h:'Jakého:'},{q:'Menstruační cyklus trvá cca...? dní',a:'28',h:'Kolik:'},{q:'Porod = narození...?',a:'ditete',h:'Čeho:'},{q:'Kojení dodává dítěti...?',a:'protilátky',h:'Co:'},{q:'Antikoncepce brání...?',a:'otehotneni',h:'Čemu:'},{q:'Pohlavně přenosné nemoci se přenášejí...?',a:'pohlavnim stykem',h:'Jak:'},{q:'Embryo se vyvíjí v...?',a:'deloze',h:'Kde:'},{q:'Dvojčata mohou být jednovaječná a...?',a:'dvojvajecna',h:'A jaká:'},{q:'Chromozomy XX = ...?',a:'divka',h:'Kdo:'}];
DATA.pr9_genetika=[{q:'DNA obsahuje genetickou...?',a:'informaci',h:'Co:'},{q:'Gen kóduje...?',a:'protein',h:'Co:'},{q:'Alela je varianta...?',a:'genu',h:'Čeho:'},{q:'Mendel je zakladatel...?',a:'genetiky',h:'Čeho:'},{q:'Dominantní alela se projeví...?',a:'vzdy',h:'Kdy:'},{q:'Recesivní alela se projeví jen v...?',a:'homozygotnim stavu',h:'V čem:'},{q:'Mutace je změna v...?',a:'dna',h:'V čem:'},{q:'Chromosom člověka: 22 párů + ...?',a:'pohlavni',h:'A jaké:'},{q:'Klonování = ...?',a:'geneticka kopie',h:'Co:'},{q:'GMO = geneticky...?',a:'modifikovany organismus',h:'Co:'},{q:'Genová terapie léčí...?',a:'geneticke nemoci',h:'Co:'},{q:'Downův syndrom = trisomie...?',a:'21',h:'Čeho:'},{q:'Krevní skupiny jsou dědičné? (ano/ne)',a:'ano',h:'Odpověz:'},{q:'Barva očí je...?',a:'dedicna',h:'Jaká:'},{q:'Genetický kód je...?',a:'univerzalni',h:'Jaký:'}];
